### ISSUE TITLE
Serializing binary data

### ISSUE THREAD

**Issue by romisak** [msgpack/msgpack-cli#100]
Hi, 

How do I serialize byte array as "bin" and not "str"? I thought this code with isBinary set to true should work, but it keeps returning "str" data anyway.

MessagePackObject obj = new MessagePackObject(new byte[] { 1, 2, 3 }, isBinary: true);
var serializer = SerializationContext.Default.GetSerializer<MessagePackObject>();
byte[] serialized = serializer.PackSingleObject(obj);
Console.WriteLine("Serialized: {0}", BitConverter.ToString(serialized))

This is output:
Serialized: A3-01-02-03

While I would expect the following output:
Serialized: C4-03-01-02-03

Thanks, Roman

**Comment by yfakariya** [comment]
Please ensure `SerializationContext.SerializationCompatibilityOptions.PackerCompatibilityOptions`' `PackBinaryAsRaw` bit is off. Note that as of 0.6.0 beta3, this value is clear by default, but it was set before 0.6.0 beta3 to prefer backward compatibility.

**Comment by romisak** [comment]
Thanks, that's exactly what I needed.

**Comment by yfakariya** [comment]
Close because the answer should be enough.
