### ISSUE TITLE
Generating Serializers with EnumSerializationMethod.ByUnderlyingValue

### ISSUE THREAD

**Issue by Tinche** [msgpack/msgpack-cli#102]
Hi,

I'm using MsgPack with Unity on iOS, so I'm trying to use pregeneration of serializers (like described in https://github.com/msgpack/msgpack-cli/wiki/Xamarin-and-Unity#generate-serializers-in-advance). However, my enum serializers get generated with ```EnumSerializationMethod.ByName```, instead of by underlying value. It doesn't look like ```SerializerCodeGenerationConfiguration``` has an option for this; is there anything that can be done?

Cheers.

**Comment by yfakariya** [comment]
I forgot it... Thank you for reporting!

**Comment by yfakariya** [comment]
Fixed in 0.6.0.

**Comment by Tinche** [comment]
Excellent, thank you!
