### ISSUE TITLE
TypeInfoEncoder.cs bug

### ISSUE THREAD

**Issue by fiechter** [msgpack/msgpack-cli#108]
Decoding of objects with the attribute MessagePackRuntimeType is failing in version 0.6.

It seems as the line 72 of TypeInfoEncoder.cs  has a small bug:
Line 72: ? Elipsis + type.FullName.Substring( assemblyName.Name.Length )
This create the name including two dots. For example "Test..TestClass"

My working solution is:
Line 72: ? type.FullName.Substring( assemblyName.Name.Length )
This creates the name "Test.TestClass" which can afterwards be correctly decoded.

**Comment by yfakariya** [comment]
Thank you for reporting! I'll fix it.

**Comment by yfakariya** [comment]
Fixed in 0.6.1.
