### ISSUE TITLE
serialization deserialization time of MessagePack is slower than Json

### ISSUE THREAD

**Issue by st0326s** [msgpack/msgpack-cli#114]
The API communication we would like to use the MessagePack to speed.

Whether the speed of serialization deserialization how much different
Use the MessagePack and JSON,
We conducted a speed comparison in the following processing.

**Make Data → Culculate Time→ serialization → Culculate Time → deserialization → Culculate Time**

**■ MsgPack used**

https://github.com/msgpack/msgpack-cli/releases

Expand the zip file in the version 0.62 of the above URL
We are using the MsgPack.dll in unity3d folder.

**■ Json used**

MiniJSON

**■ test case**
1:
(Average value List was 100 times serialization deserialization of int from 0 to 10000)
Check the actual Android

2:
(Average value that was 100 times serialization de serialize the List of string from 0 to 10000)
Check the actual Android

**■ test results**
Case 1:
MsgPack:
Serialization time: 24msec
Deserialization time: 163msec
Json:
Serialization time: 28msec
Deserialization time: 70msec

Case 2:
MsgPack:
Serialization time: 38msec
Deserialization time: 283msec
Json:
Serialization time: 22msec
Deserialization time: 47msec

**■ソースコード**
```
using UnityEngine;
using System;
using System.IO;
using System.Collections;
using System.Collections.Generic;
using MiniJSON;
using MsgPack;
using MsgPack.Serialization;
using System.Linq;

public class MsgPackAndJsonCompare : MonoBehaviour {

    public int SampleCount = 100;

    private string MsgLog = "";
    private int SampleIndex = 0;

    List<long> ArrayListLong = new List<long>();
    List<string> ArrayListString = new List<string>();



    /// <summary>
    /// intデータ作成処理
    /// </summary>
    public void OnClickArrayInt()
    {
        for(int i = 0; i < 10000; i++)
        {
            ArrayListLong.Add(i);
        }
        Debug.Log("OnClickArrayInt End");
    }


    /// <summary>
    /// Stringデータ作成処理
    /// </summary>
    public void OnClickArrayString()
    {
        for (int i = 0; i < 10000; i++)
        {
            ArrayListString.Add(i.ToString());
        }
        Debug.Log("OnClickArrayString End");

    }


    /// <summary>
    /// 100回ループするテスト開始
    /// </summary>
    /// <param name="sendMode"></param>
    public void OnClickCompare(int sendMode)
    {
        SampleIndex = 0;

        for (int i = SampleIndex; i < SampleCount; i++)
        {
            MsgLog = MsgLog + ",LoopCnt=" + i.ToString();
            MsgLog = MsgLog + ",StartTime=" + DateTime.Now.Ticks.ToString();

            MainFunc(sendMode);

            MsgLog = MsgLog + " ,EndTime=" + DateTime.Now.Ticks.ToString() + "\n";
        }

        Debug.Log("Function End");


    }

    /// <summary>
    /// メイン処理
    /// </summary>
    /// <param name="compareMode"></param>
    private void MainFunc(int compareMode)
    {
        // ArrayInt-MsgPack
        if (compareMode == 0)
        {
            MsgLog = MsgLog + ",シリアライズStartTime=" + DateTime.Now.Ticks.ToString();
            var stream = new MemoryStream();
            // Create serializer instance.
            var serializer = MessagePackSerializer.Get<List<long>>();
            serializer.Pack(stream, ArrayListLong);

            //long datalen = stream.Length;

            MsgLog = MsgLog + ",シリアライズEndTime=" + DateTime.Now.Ticks.ToString();
            stream.Position = 0;
            List<long> deserializedObject = serializer.Unpack(stream);
            MsgLog = MsgLog + ",デシリアライズEndTime=" + DateTime.Now.Ticks.ToString();
        }
        // ArrayInt-Json
        else if (compareMode == 1)
        {
            MsgLog = MsgLog + ",シリアライズStartTime=" + DateTime.Now.Ticks.ToString();
            string serialized = Json.Serialize(ArrayListLong);

            int ilenb = System.Text.Encoding.GetEncoding(65001).GetByteCount(serialized);

            MsgLog = MsgLog + ",シリアライズEndTime=" + DateTime.Now.Ticks.ToString();
            List<System.Object> deserializedDoubleList = Json.Deserialize(serialized) as List<System.Object>;
            List<long> longList = deserializedDoubleList.OfType<long>().ToList();
            MsgLog = MsgLog + ",デシリアライズEndTime=" + DateTime.Now.Ticks.ToString();

        }
        // ArrayString-MsgPack
        else if (compareMode == 2)
        {
            MsgLog = MsgLog + ",シリアライズStartTime=" + DateTime.Now.Ticks.ToString();
            var stream = new MemoryStream();
            // Create serializer instance.
            var serializer = MessagePackSerializer.Get<List<string>>();
            serializer.Pack(stream, ArrayListString);

            long datalen = stream.Length;

            MsgLog = MsgLog + ",シリアライズEndTime=" + DateTime.Now.Ticks.ToString();
            stream.Position = 0;
            List<string> deserializedObject = serializer.Unpack(stream);
            MsgLog = MsgLog + ",デシリアライズEndTime=" + DateTime.Now.Ticks.ToString();
        }
        // ArrayString-Json
        else if (compareMode == 3)
        {
            MsgLog = MsgLog + ",シリアライズStartTime=" + DateTime.Now.Ticks.ToString();
            string serialized = Json.Serialize(ArrayListString);

            int ilenb = System.Text.Encoding.GetEncoding(65001).GetByteCount(serialized);

            MsgLog = MsgLog + ",シリアライズEndTime=" + DateTime.Now.Ticks.ToString();
            List<System.Object> deserializedDoubleList = Json.Deserialize(serialized) as List<System.Object>;
            List<string> longList = deserializedDoubleList.OfType<string>().ToList();
            MsgLog = MsgLog + ",デシリアライズEndTime=" + DateTime.Now.Ticks.ToString();

        }
    }


    public void OnclickLog()
    {
        StartCoroutine(LogDisp());

    }


    IEnumerator LogDisp()
    {
        string[] LogArray = MsgLog.Split('\n');

        int maxloop = LogArray.Length;
        int i = 0;
        while (i < maxloop)
        {
            Debug.Log("Log=" + LogArray[i]);

            yield return 0;

            i++;

        }
    }
    }
```

**■ Problems**
Statement that people of MessagePack is faster and has attracted the information on the net
Often seen I, but rather than be handled by MessagePack in my source
For those of JSON is speed is fast, it is suspect than is wrong way.

**Comment by yfakariya** [comment]
Thank you for report. The time to re-tune is coming :)

**Comment by st0326s** [comment]
Thank you to answer the question.

Although I want you to tell me if you know,
Will become faster on the theory as compared to the time of serialization and de-serialization of msgpack is json?

While Msgpack is that it is possible to reduce the capacity, time of serialization and de-serialization takes more than Json, How can we think that it can shorten the time to communicate.

Will not get let the idea of the author like?

**Comment by yfakariya** [comment]
There are multiple arguments for it.
1) MiniJSON is not a serializer srtictly. It has very comact footprint. It should be compared to Packer/Unpacker API.
2) For string, there are no advantages for binary serialization because it is still required to encode/decode strtings. So binary serialization should be great for many numeric values.
3) Text based deserialization should require more validation than binary deserialization if they concern them identically.

In spite of them, I guess there are some space to optimization especially in Unpacker class and List<T> handling.

**Comment by st0326s** [comment]
Thank you for your explanation for a number of factors.
Such as the size of the post-serialization that MessagePack is winning the
We were able to prove in the measurement.
Since the de-serialization time is the bottleneck, it is possible to study there, my own use and said that by using the sample will try to validate be whether correct or.
