### ISSUE TITLE
Msgpack RegisterOverride not being used when deserializing.

### ISSUE THREAD

**Issue by joaoportela** [msgpack/msgpack-cli#116]
I have to do a special serializer for the datetime types, but I cannot get it to be called when deserializing an object.

Here is the sample code from my linqpad tests:

    void Main()
    {
        var context = new SerializationContext {
            SerializationMethod = SerializationMethod.Map,
            EnumSerializationMethod = EnumSerializationMethod.ByName,
            CompatibilityOptions = {
                PackerCompatibilityOptions = PackerCompatibilityOptions.None
            }
        };
        context.Serializers.RegisterOverride(new DateTimeToNetworkSerializer(context));

        // arranje
        var testSerializer = context.GetSerializer<TestDateTime>();
        var expected = new TestDateTime { Timestamp = new DateTime(2015, 03, 26, 12, 12, 12, DateTimeKind.Utc) };

        // act
        var bytes = testSerializer.PackSingleObject(expected);
        var testDateTime = testSerializer.UnpackSingleObject(bytes);

        // assert
        Console.WriteLine(testDateTime.Timestamp.Ticks == expected.Timestamp.Ticks);
        Console.WriteLine(testDateTime.Timestamp.Kind == expected.Timestamp.Kind);
        Console.WriteLine(testDateTime.Timestamp);
        Console.WriteLine(testDateTime.Timestamp.Kind);
    }
    // Define other methods and classes here

    class DateTimeToNetworkSerializer : MessagePackSerializer<DateTime>
    {
        public DateTimeToNetworkSerializer() :
            this(SerializationContext.Default) { }

        public DateTimeToNetworkSerializer(SerializationContext context)
            : base(context) { }

        protected override void PackToCore(Packer packer, DateTime datetime)
        {
            Console.WriteLine("packing...");
            packer.Pack(GetTicks(datetime));
        }

        protected override DateTime UnpackFromCore(Unpacker unpacker)
        {
            Console.WriteLine("upacking...");
            long ticks = unpacker.LastReadData.AsInt64();

            return FromTicks(ticks);
        }

        #region DateTime serialization. Stores and reads ticks, assumes UTC.
        // Ticks is defined as:
        // - The value of this property represents the number of 
        //   100-nanosecond intervals that have elapsed since 12:00:00 midnight, 
        //   January 1, 0001 (0:00:00 UTC on January 1, 0001, in the Gregorian calendar),
        //   which represents DateTime.MinValue. It does not include the number of ticks 
        //   that are attributable to leap seconds.
        // https://msdn.microsoft.com/en-us/library/system.datetime.ticks%28v=vs.110%29.aspx
        //
        // *In summary*: 1 tick = 100-nanosecond. Epoch = 0:00:00 UTC on January 1, 0001

        private long GetTicks(DateTime timestamp)
        {
            if (timestamp.Kind == DateTimeKind.Utc)
                return timestamp.Ticks;

            if (System.Diagnostics.Debugger.IsAttached)
                System.Diagnostics.Debugger.Break(); // UTC was expected.

            return timestamp.ToUniversalTime().Ticks;
        }

        private DateTime FromTicks(long ticks)
        {
            return new DateTime(ticks, DateTimeKind.Utc);
        }
        #endregion
    }

    public class TestDateTime
    {
        public DateTime Timestamp { get; set; }
    }

And this is the output:

    packing...
    True
    False
    26/03/2015 12:12:12
    Unspecified

As you can see the serializer is not used for unpacking. Am I doing something wrong? According to my tests, doing the same thing for Guid doesn't have the same issue.

**Comment by joaoportela** [comment]
I think I have figured it out.

When deserializing it is looking for the `MessagePackSerializer<DateTime?>` deserializer instead of `MessagePackSerializer<DateTime>`, as such it doesn't find the serializer that I have registered.

Registering a `MessagePackSerializer<DateTime?>` seems to fix the problem.

**Comment by yfakariya** [comment]
You are right. I'm trying fix this problem adding new API to register nullable companion simulary (but it causes Unity AOT issue so it takes additional time to solve).

**Comment by yfakariya** [comment]
This issue fixed in 0.6.3. Please check it.
