### ISSUE TITLE
[INFO] Some things to note by users.

### ISSUE THREAD

**Issue by aensidhe** [msgpack/msgpack-cli#117]
1. Default serializer for Nullable types fallback to serializer of underlying type (e.g. `int?` to `int`, etc), except for `DateTime`. There is a related bug #116. I suggest to adjust behaviour serialization of `DateTimeOffset` to be identical with `DateTime`, right now they are different.

2. Default enum serializer relies on assemblies, generated by `Reflection.Emit` on every call of `SerializationContext` constructor, so `SerializationContext` better be reused. Creating it on per-request basis will give a huge performance problems. I do not know if `SerializationContext` thread-safe or not. I suggest caching of assemblies in default enum serializer.

Hope, it's useful.

**Comment by yfakariya** [comment]
Thank you for suggestions! As you say, `DateTimeOffset` serializer's behavior should be same as `DateTime` one. I will fix it. But I cannot understand well for second suggestion. Is "`SerializationContext` is designed as thread-safe" correct answer for it?

**Comment by aensidhe** [comment]
It was not a real suggestion. Yep, it's good that `SerializationContext` is thread-safe. Other problem is that if you have several instances of that context and use it for serializing of one enum type, each instance of default enum serializer will generate a dynamic assembly. Which can be a perfomance problem. So, it is better to reuse context.

**Comment by yfakariya** [comment]
Yes, as you said, reusing context is better obviously. It is free for users to choice them (it is reason why `SerializerContext` is implemented as thread-safe). In addition, `SerializationContext` is "context" of serialization and they have own serializer instances and settings by design.
So, what did you mean about? I think I do not understand your post well.

**Comment by yfakariya** [comment]
The first issue was fixed in 0.6.3 (sorry I wrote wrong commit log). Please check it.

**Comment by aensidhe** [comment]
Thank you. It's good.
