### ISSUE TITLE
Exception when serializing generic property

### ISSUE THREAD

**Issue by KingTopas** [msgpack/msgpack-cli#119]
Two classes:

public abstract class A<TId>
{
	public virtual TId Id { get; set; }
}

public class B : A<int>: 
{
}

An exception is thrown when creating serializer for an instance of class B:

Void set_Id method (Int32) can not be solved because the declarative type descriptor methods A`1 [tid] is generic. Explicitly specify the type of declaration GetMethodFromHandle.

System.Reflection.MethodBase.GetMethodFromHandle(RuntimeMethodHandle handle) +11045317
   MsgPack.Serialization.EmittingSerializers.FieldBasedSerializerEmitter.CreateConstructor() in d:\build\msgpack-cli-latest\src\MsgPack\Serialization\EmittingSerializers\FieldBasedSerializerEmitter.cs:448
   MsgPack.Serialization.EmittingSerializers.SerializerEmitter.CreateInstance(SerializationContext context, PolymorphismSchema schema) in d:\build\msgpack-cli-latest\src\MsgPack\Serialization\EmittingSerializers\SerializerEmitter.cs:130
   MsgPack.Serialization.EmittingSerializers.<>c__DisplayClass6f.<CreateSerializerConstructor>b__6e(SerializationContext context) in d:\build\msgpack-cli-latest\src\MsgPack\Serialization\EmittingSerializers\ILEmittingSerializerBuilder`2.cs:1028
   MsgPack.Serialization.AbstractSerializers.SerializerBuilder`3.BuildSerializerInstance(SerializationContext context, Type concreteType, PolymorphismSchema schema) in d:\build\msgpack-cli-latest\src\MsgPack\Serialization\AbstractSerializers\SerializerBuilder`3.cs:201
   MsgPack.Serialization.MessagePackSerializer.CreateInternal(SerializationContext context, PolymorphismSchema schema) in d:\build\msgpack-cli-latest\src\MsgPack\Serialization\MessagePackSerializer.cs:308
   MsgPack.Serialization.SerializationContext.GetSerializer(Object providerParameter) in d:\build\msgpack-cli-latest\src\MsgPack\Serialization\SerializationContext.cs:691
   MsgPack.Serialization.MessagePackSerializer.Get(SerializationContext context, Object providerParameter) in d:\build\msgpack-cli-latest\src\MsgPack\Serialization\MessagePackSerializer.cs:209
   MsgPack.Serialization.MessagePackSerializer.Create(SerializationContext context) in d:\build\msgpack-cli-latest\src\MsgPack\Serialization\MessagePackSerializer.cs:106
   MsgPack.Serialization.MessagePackSerializer.Create() in d:\build\msgpack-cli-latest\src\MsgPack\Serialization\MessagePackSerializer.cs:80

**Comment by KingTopas** [comment]
Seems the editor can't handle tags...

public abstract class A&lt;TId&gt;
 {
 public virtual TId Id { get; set; }
 }

public class B : A&lt;int&gt;
 {
 }

**Comment by yfakariya** [comment]
I could not reproduce this, but if the `Id` property setter was NOT public it looked liked to be reproduced. Was the `Id` property public? If so, it was bug and I'll fix it.

**Comment by KingTopas** [comment]
Yes, sorry for noc mentioning it earlier. The whole declaration of Id is:

public virtual TId Id
{
	get;
	internal set;
}

**Comment by yfakariya** [comment]
OK, thank you. I'll fix it.
