### ISSUE TITLE
PolymorphismSchema.Constructors.cs uses ReadOnlyCollection<T> (MsgPack.Unity3D.Full.csproj)

### ISSUE THREAD

**Issue by MichihitoManaka** [msgpack/msgpack-cli#123]
My  environment:
Messagepack-cli 0.6.3
Use in source code(MsgPack.Unity3D.Full.csproj)

Unity 5.2.1p3(Mac)

Initialization of static readonly members in Unity are special.

It actually becomes null in the constructor by Unity environment.
(ReadOnlyCollection<T> does not allow null)

Other 'ReadOnlyCollection<T>' is not used in Unity.
(by #define UNITY)

Is this code(PolymorphismSchema.Constructors.cs) for the Unity design?
If different, I want you to make corrections.

Thanks,

**Comment by yfakariya** [comment]
Would you give me the stack trace of the exception? It is required source, so I'll add workaround (as long as your report, this looks Unity's bug)

**Comment by MichihitoManaka** [comment]
It is a Unity console output of a minimum test environment.
Messagepack-cli 0.6.3(MsgPack.Unity3D.Full.csproj)
Unity 5.2.1p2(Mac)

If necessary, I can send you a unitypackage(This minimum test environment).

Thanks,

===========================================================


ArgumentNullException: Argument cannot be null.
Parameter name: list
System.Collections.ObjectModel.ReadOnlyCollection`1[MsgPack.Serialization.PolymorphismSchema]..ctor (IList`1 list) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.Collections.ObjectModel/ReadOnlyCollection.cs:53)
MsgPack.Serialization.PolymorphismSchema..ctor () (at Assets/MsgPack/Serialization/PolymorphismSchema.Constructors.cs:45)
MsgPack.Serialization.PolymorphismSchema..cctor ()
Rethrow as TypeInitializationException: An exception was thrown by the type initializer for MsgPack.Serialization.PolymorphismSchema
MsgPack.Serialization.DefaultSerializers.GenericSerializer.Create[TestClass] (MsgPack.Serialization.SerializationContext context, MsgPack.Serialization.PolymorphismSchema schema) (at Assets/MsgPack/Serialization/DefaultSerializers/GenericSerializer.cs:50)
MsgPack.Serialization.SerializationContext.GetSerializer[TestClass] (System.Object providerParameter) (at Assets/MsgPack/Serialization/SerializationContext.cs:677)
MsgPack.Serialization.MessagePackSerializer.Get[TestClass] (MsgPack.Serialization.SerializationContext context, System.Object providerParameter) (at Assets/MsgPack/Serialization/MessagePackSerializer.cs:209)
MsgPack.Serialization.MessagePackSerializer.Get[TestClass] (MsgPack.Serialization.SerializationContext context) (at Assets/MsgPack/Serialization/MessagePackSerializer.cs:164)
MsgPack.Serialization.MessagePackSerializer.Get[TestClass] () (at Assets/MsgPack/Serialization/MessagePackSerializer.cs:123)
TestSerialize`1[TestClass].Pack (.TestClass obj) (at Assets/TestSerialize.cs:11)
TestMain.Awake () (at Assets/TestMain.cs:15)

**Comment by MichihitoManaka** [comment]
In Unity programming, the constructor is not recommended if you have inherited the MonoBehaviour.

Similarly to. initialization of static readonly also different from that of the C # looks like a specification.

Thanks,

**Comment by yfakariya** [comment]
Would you send me your unitypackage? I cannot repro the problem in Unity 5.2.1p3 with iOS build (did you use another build such as Standalone MAC?)

**Comment by MichihitoManaka** [comment]
It will send the unitypackage(use Contact GitHub).

Additional description:

There is no NuGet the Mac environment.
Therefore, we have copied(UnityProject) the contents of the "MsgPack.Unity3D.Full.csproj".
This is because, we want to use in the source code(not a dll).
And, this problem occurs when Unity build(source code).
(When using the "unity3d\MsgPack.dll"(0.6.3) problem does not occur)

===============================================================================
Another matter:

"unity3d-full\MsgPack.dll"(0.6.3) can not be loaded.

Unhandled Exception: System.Reflection.ReflectionTypeLoadException: The classes in the module cannot be loaded.
  at (wrapper managed-to-native) System.Reflection.Assembly:GetTypes (bool)
  at System.Reflection.Assembly.GetTypes () [0x00000] in <filename unknown>:0 
  at Mono.CSharp.RootNamespace.ComputeNamespaces (System.Reflection.Assembly assembly, System.Type extensionType) [0x00000] in <filename unknown>:0 
  at Mono.CSharp.RootNamespace.ComputeNamespace (Mono.CSharp.CompilerContext ctx, System.Type extensionType) [0x00000] in <filename unknown>:0 
  at Mono.CSharp.GlobalRootNamespace.ComputeNamespaces (Mono.CSharp.CompilerContext ctx) [0x00000] in <filename unknown>:0 
  at Mono.CSharp.Driver.LoadReferences () [0x00000] in <filename unknown>:0 
  at Mono.CSharp.Driver.Compile () [0x00000] in <filename unknown>:0 
  at Mono.CSharp.Driver.Main (System.String[] args) [0x00000] in <filename unknown>:0 

The class System.IO.HandleInheritability could not be loaded, used in System.Core, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
The class System.IO.HandleInheritability could not be loaded, used in System.Core, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
The class System.IO.Pipes.PipeAccessRights could not be loaded, used in System.Core, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
The class System.IO.Pipes.PipeAccessRights could not be loaded, used in System.Core, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
The class System.IO.Pipes.PipeDirection could not be loaded, used in System.Core, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
The class System.IO.Pipes.PipeDirection could not be loaded, used in System.Core, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
The class System.IO.Pipes.PipeOptions could not be loaded, used in System.Core, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
The class System.IO.Pipes.PipeOptions could not be loaded, used in System.Core, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
The class System.IO.Pipes.PipeTransmissionMode could not be loaded, used in System.Core, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
The class System.IO.Pipes.PipeTransmissionMode could not be loaded, used in System.Core, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089

**Comment by MichihitoManaka** [comment]
"unitypackage" did not the format can be attached in the "Contact GitHub".
Would you like to do?

**Comment by yfakariya** [comment]
Thank you for information. I could not repro both of DLL and source code. I guess the problem was caused by static initialization order as you suggested, and I found there are other issues related to the Unity's compiler. Please try next (0.6.5) version and its polished `mpu.exe -l` tool to generate available source tree for Unity. 

For second problem, would you look your build settings that whether you use ".net 2.0" or ".net 2.0 subset". If you use latter, you cannot use MsgPack.Unity3D.Full/MsgPack.dll, you must use MsgPack.Unity3D/MsgPack.dll instead. The non-full Unity3D DLL does not require System.dll and System.Core dll, so it should work fine.

**Comment by MichihitoManaka** [comment]
Thank you.
I understand. We will wait for 0.6.5.

**Comment by yfakariya** [comment]
Is this issue solved?

**Comment by MichihitoManaka** [comment]
Yes, we confirm the operation.
Thank you.

**Comment by yfakariya** [comment]
Thank you replying!
