### ISSUE TITLE
always attempts to deserialize DataMember

### ISSUE THREAD

**Issue by BrannonKing** [msgpack/msgpack-cli#126]
Using the code below, I get an error deserializing stating that there is no data for the item at index 2. That is correct. It was null when I serialized it. I want it to be null when I deserialize it. The fact that there is no data for it is not an error. How can I work around that error? I have a custom serializer for the interface, but I don't get a breakpoint hit for `UnpackFromCore` or `UnpackNil` for the second item.

```csharp
		[DataContract]
		public class ContainerWrapper
		{
			[DataMember(Order = 1, IsRequired = false)]
			public ISerializedContainer Container { get; set; }

			[DataMember(Order = 2, IsRequired = false)]
			public ISerializedContainer AlwaysNull { get; set; }
		}
```

**Comment by yfakariya** [comment]
There are some points for this issue.

1. When you use `DateMemberAttribute` with 1-based `Order` and you do NOT use custom serializer, you must set `SerializationContext.CompatibilityOptions.OneBoundDataMemberOrder` to `true`, and then use the context to get serializer instance.
1. When you use your custom serializer, don't forget to register them via `SerializationContext.Serializers.RegisterOverride()` method, and then use the context to get serializer instance.

Note that mapping between `DataMemberAttribute.Order` and serialized array indexes is your task.

**Comment by BrannonKing** [comment]
Enabling `SerializationContext.CompatibilityOptions.OneBoundDataMemberOrder` changes the error from "index 2" to "index 1". Unfortunately it did not make the error go away. I was using the `Register` method to add my custom serializer rather than `RegisterOverride`. I expected that I wouldn't need the latter unless I was trying to change behavior for some common type. I know that my custom serializer is getting hit, and that it works right as long as the object being (de)serialized is not null.

**Comment by yfakariya** [comment]
Thank you for response. Sorry for my suggestions were pointless (you had been right for them) and I misunderstood your first post. Would you show me the stack trace?

**Comment by BrannonKing** [comment]
Here is the exception:

```
MsgPack.InvalidMessagePackStreamException was unhandled by user code
  HResult=-2146233088
  Message=Items at index '2' is missing.
  Source=MsgPack.Serialization.EmittingSerializers.GeneratedSerealizers2
  StackTrace:
       at MsgPack.Serialization.EmittingSerializers.Generated.Kts_Remoting_Tests_SerializerTests_ContainerWrapperSerializer2.UnpackFromCore(Unpacker )
       at MsgPack.Serialization.MessagePackSerializer`1.UnpackFrom(Unpacker unpacker)
       at MsgPack.Serialization.MessagePackSerializer`1.MsgPack.Serialization.IMessagePackSerializer.UnpackFrom(Unpacker unpacker)
       at MsgPack.Serialization.MessagePackSerializerExtensions.Unpack(IMessagePackSerializer source, Stream stream)
       at CommonSerializer.MsgPack.Cli.MsgPackCommonSerializer.Deserialize(Stream stream, Type type) in C:\Users\notac\Documents\CommonSerializer\CommonSerializer.MsgPack.Cli\MsgPackCommonSerializer.cs:line 79
       at CommonSerializer.MsgPack.Cli.MsgPackCommonSerializer.Deserialize[T](Stream stream) in C:\Users\notac\Documents\CommonSerializer\CommonSerializer.MsgPack.Cli\MsgPackCommonSerializer.cs:line 97
       at Kts.Remoting.Tests.SerializerTests.TestPartialCreation() in C:\Users\notac\Documents\CommonSerializer\CommonSerializer.Tests\SerializerTests.cs:line 201
  InnerException: 
```

**Comment by yfakariya** [comment]
Thank you, but it looks just a data problem. Could you show serialized bytes array(it should be begun with 0x92) or your custom serializer code to reproduce?

**Comment by BrannonKing** [comment]
Here is sample code that throws the exception:

```csharp
using System;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using MsgPack;
using MsgPack.Serialization;

namespace DemoMsgPackFailure
{
	public class Program
	{
		public interface ITester
		{
		}

		public class Tester : ITester
		{
			public string[] A { get; set; }
		}

		[DataContract]
		public class TesterContainer
		{
			[DataMember(Order = 1, IsRequired = false)]
			public ITester Tester1 { get; set; }

			[DataMember(Order = 2, IsRequired = false)]
			public ITester AlwaysNullTester { get; set; }
		}

		internal class TesterSerializer : MessagePackSerializer<ITester>
		{
			public TesterSerializer(SerializationContext context)
				: base(context)
			{
				// If the target objects has complex (non-primitive) objects,
				// you can get serializers which can handle complex type fields.
				// And then, you can cache them to instance fields of this custom serializer.
			}

			protected override void PackToCore(Packer packer, ITester objectTree)
			{
				Console.WriteLine("PackToCore");
				var arr = ((Tester)objectTree).A;
				packer.PackArrayHeader(arr);
				packer.PackArray(arr);
			}

			protected override ITester UnpackFromCore(Unpacker unpacker)
			{
				Console.WriteLine("UnpackFromCore");
				
				if (!unpacker.IsArrayHeader)
					throw new SerializationException("Invalid position.");

				var ret = new Tester();
				long len;
				if (!unpacker.ReadArrayLength(out len)) // why is the method not named ReadArrayHeader?
					return ret;

				var arr = new string[len];
				for (int i = 0; i < len; i++)
				{
					string val;
					if (!unpacker.ReadString(out val))
						throw new SerializationException("Invalid data format.");
						
					arr[i] = val;
				}
				ret.A = arr;
				return ret;
			}

			protected override void UnpackToCore(Unpacker unpacker, ITester collection)
			{
				Console.WriteLine("UnpackToCore");
				base.UnpackToCore(unpacker, collection);
			}

			protected override ITester UnpackNil()
			{
				Console.WriteLine("UnpackNil");
				return base.UnpackNil();
			}
		}
		public static void Main()
		{
			var item1 = new TesterContainer { Tester1 = new Tester { A = new[]{"a", "b"} } };
			var context = new SerializationContext();
			context.Serializers.RegisterOverride(new TesterSerializer(context));

			var serializer = context.GetSerializer<TesterContainer>();

			using (var ms = new MemoryStream())
			{
				serializer.Pack(ms, item1);
				ms.Position = 0;
				var item2 = serializer.Unpack(ms);

				if (!((Tester)item1.Tester1).A.SequenceEqual(((Tester)item2.Tester1).A))
					throw new Exception();
			}
		}
	}
}
```

**Comment by BrannonKing** [comment]
@yfakariya, have you had a chance to try this sample code?

**Comment by yfakariya** [comment]
Sorry, I missed the additional post...

It is your custom serializer's bug. I guess you should want to pack your `Tester` object as `[['a', 'b']]`, but you serialized as `[['a', 'b'], <missing>]` because you called `PackArrayHeader(arr)` to allocate 2 element array, called `PackArray(arr)` to pack `A` as array including its header, and did not specify "2nd member" of the `Tester` object. And then, you unpacked as  `[['a', 'b']`, so remaining `nil` was skipped as `<missing>` element of above.
The solution is use `PackArrayHeader(1)` instead of `PackArrayHeader(arr)` on your `PackCore` override. It should be specify a number of members you will serialize.

**Comment by BrannonKing** [comment]
Thanks for the response. I guess I'm having trouble wrapping my head around the asymmetry of the packer read/write array API. However, this appears to work:

```csharp
		protected override void PackToCore(Packer packer, ISerializedContainer objectTree)
		{
			var list = new List<byte[]>();
			byte[] bytes;
			while (((MsgPackSerializedContainer)objectTree).Queue.TryDequeue(out bytes))
				list.Add(bytes); // yes, I want it to leave the thing empty

			packer.Pack(list);
		}

		protected override ISerializedContainer UnpackFromCore(Unpacker unpacker)
		{
			var ret = new MsgPackSerializedContainer();
			var list = unpacker.Unpack<List<byte[]>>();

			foreach (var bytes in list)
				ret.Queue.Enqueue(bytes);

			return ret;
		}
```

I assume that packing a list of byte arrays does not do any encoding on the data. I'll go with this new code for now unless you suggest some alternate approach that is more performant.

**Comment by yfakariya** [comment]
Yes, the point is symmetry between packing and unpacking. And your alternative just says that the your serializer just treat `MsgPackSerializedContainer` as a collection of byte array instead of object (it looks like [collection serializer](https://github.com/msgpack/msgpack-cli/blob/master/src/MsgPack/Serialization/DefaultSerializers/System_Collections_Generic_Queue_1MessagePackSerializer%601.cs) . It is a valid optimization, but it assumes the `ISerializedContainer` is a collection or should have single collection member eternally.

**Comment by BrannonKing** [comment]
Yes, my `MsgPackSerializedContainer` is a private type that I don't want exposed anywhere. The interface is empty; it's essentially a placeholder for a black box of sorts.
