### ISSUE TITLE
CoreCLR support.

### ISSUE THREAD

**Issue by aensidhe** [msgpack/msgpack-cli#128]
Hi.

[https://github.com/msgpack/msgpack-cli/wiki](Wiki) states that CoreCLR support will be added in 0.6.0. We are using 0.6.2 and there are no any support. We tried 0.6.5 and there are no support either. 

Right now we are moving to CoreCLR and it would be nice to know if you plan to support CoreCLR in any near future. 

Thank you.

**Comment by yfakariya** [comment]
Agree.

**Comment by yfakariya** [comment]
It is blocked with corefx's `TypeInfo.GetInterfaceMap` implementation.

**Comment by adamhathcock** [comment]
I saw the 0.7.0 alpha 2 package but it's built against pre-RC2 correct?

I'd like to build itself but don't see any project.json.  How is it built?

Does nothing work because of the implementation you mentioned?

**Comment by yfakariya** [comment]
The project.json is here. https://github.com/msgpack/msgpack-cli/tree/0.7/src/MsgPack/
(It is because the assembly name is determined by containing directory name)

> Does nothing work because of the implementation you mentioned?
Yes. Serializers should not work at all because of `PlatformNotSupportedException`.

**Comment by adamhathcock** [comment]
Thanks!  I don't know why I didn't look for the branch.

**Comment by yfakariya** [comment]
.NET Core was supported from 0.7.0. So I've close this issue.
