### ISSUE TITLE
How can i serializer a type of List<List<T>>

### ISSUE THREAD

**Issue by dearlulu** [msgpack/msgpack-cli#129]
A type of List<T>,I can custom serializer success,but i can't serializer type of  List<List<T>>

the problem is 

protected override List<List<T>> UnpackFromCore(Unpacker unpacker)

my List<T> custom serializer is this, exception handling is omitted ;

protected override List<ActivityConf> UnpackFromCore(Unpacker unpacker)
 {
 MessagePackSerializer<ActivityConf> _itemSerializer = SerializerMgr.Instance._context.GetSerializer<ActivityConf>(); 
 var count = UnpackHelpers.GetItemsCount(unpacker);
 var result = new List<ActivityConf>();
 for (int i = 0; i < count; i++)
 {
 ActivityConf item;
 if (!unpacker.IsArrayHeader && !unpacker.IsMapHeader)
 {
 item = _itemSerializer.UnpackFrom(unpacker);
 }
 else
 {
 using (var subtreeUnpacker = unpacker.ReadSubtree())
 {
 item = _itemSerializer.UnpackFrom(subtreeUnpacker);
 }
 }
 result.Add(item);
 }
 return result;
 }

How can i do the List<List<T>>

**Comment by dearlulu** [comment]
this code can solve the problem
	protected override void PackToCore(Packer packer, List<List<Conf2>> objectTree0)
	{
		MessagePackSerializer<Conf2> _itemSerializer = SerializerMgr.Instance._context.GetSerializer<Conf2>();
		List<Conf2>[] objectTree = objectTree0.ToArray();
		packer.PackArrayHeader(objectTree.Length);
		foreach (var item2 in objectTree)
		{	
			packer.PackArrayHeader(item2.ToArray().Length);
			foreach (var item in item2){
				_itemSerializer.PackTo(packer, item);
			}
		}
	}

	protected override List<List<Conf2>> UnpackFromCore(Unpacker unpacker)
	{
		MessagePackSerializer<Conf2> _itemSerializer = SerializerMgr.Instance._context.GetSerializer<Conf2>();
		if (!unpacker.IsArrayHeader)
		{
			throw SerializationExceptions.NewIsNotArrayHeader();
		}
		
		var countOut = UnpackHelpers.GetItemsCount(unpacker);//10
		var result = new List<List<Conf2>>();

		if (!unpacker.IsArrayHeader)
		{
			throw SerializationExceptions.NewIsNotArrayHeader();
		}
		
		for (int i = 0; i < countOut; i++)
		{
			if (!unpacker.Read())
			{
				throw SerializationExceptions.NewMissingItem(i);
			}
			List<Conf2> item2 = new List<Conf2>();
			var countInner = UnpackHelpers.GetItemsCount(unpacker);

			for (int l = 0; l < countInner; l++)
			{
				Conf2 item;
				if (!unpacker.Read())
				{
					throw SerializationExceptions.NewMissingItem(i);
				}
				if (!unpacker.IsArrayHeader && !unpacker.IsMapHeader)
				{
					item = _itemSerializer.UnpackFrom(unpacker);
				}
				else
				{
					using (var subtreeUnpacker = unpacker.ReadSubtree())
					{
						item = _itemSerializer.UnpackFrom(subtreeUnpacker);
					}
				}
				item2.Add(item);
			}
			result.Add(item2);
		}
		return result;
	}

**Comment by yfakariya** [comment]
Did you ask how we implement custom serializer for `List<List<T>>`? Most easier way to use `SerializerGenerator` or `mpu.exe -s` to generate serializer source code via CodeDOM. It is not pretty, but it has essence for implementation. And your 2nd code looks well.
If you intend different question, please give us what your problem is...

P.S.
`UnpackHelpers` is NOT public API, please avoid to use it if you can.

**Comment by yfakariya** [comment]
Close because it is no response for answer. It is welcome to reopen for further question. Thank you for contribution.
