### ISSUE TITLE
Release notes for 6.0 should add another breaking change

### ISSUE THREAD

**Issue by drewnoakes** [msgpack/msgpack-cli#130]
The change in serialisation of DateTime (from unix millis to native) is a breaking change but is not listed as such. This broke our application today.

https://github.com/msgpack/msgpack-cli/releases/tag/0.6.0

**Comment by yfakariya** [comment]
I'm sorry, and you are absolutely right. I've fixed it.

**Comment by drewnoakes** [comment]
Thanks.
