### ISSUE TITLE
[question] Can I extract Object info from MessagPackObject 

### ISSUE THREAD

**Issue by sueds** [msgpack/msgpack-cli#131]
Hi, 

I'm using a simple wrapper around message pack  and I need to read object info from messagePackobject. For instance how can I know which type the messagepackobject is representing. When you do read item and get the data I didn't find a way to know which type it was.

**Comment by yfakariya** [comment]
`MessagePackObject` only know structure of the stream, and it is array, map, or primitive(integers, reals, and bytes). Serialiarizers translates(maps recursively) between message pack object tree and your objects. Therefore, you can investigate whether the object represents array, map, integer, etc. with `IsTypeOf<T>`, `IsList` and `IsMap` method (and call it to the items of arrays/maps), but cannot investigate source .NET type from the `MessagePackObject` (it also means you can "deserialize" another object when the structure matches).
Is it help you?

**Comment by sueds** [comment]
Yes it does help. I'll try to see how I can implementing it. Thanks.
