### ISSUE TITLE
SerializerAssemblyGenerationConfiguration does not have Namespace configuration

### ISSUE THREAD

**Issue by neuecc** [msgpack/msgpack-cli#138]
`SerializerCodeGenerationConfiguration` have Namespace but `SerializerAssemblyGenerationConfiguration` does not have Namespace.
Would you add Namespace config?

**Comment by yfakariya** [comment]
As you said, there are no options to tweak generated serializers type names including their namespaces. I'll add it the next release.

**Comment by yfakariya** [comment]
This feature was added in 0.7.0-alpha3, so I've closed it.
