### ISSUE TITLE
How to reference generated serializer assembly in Unity?

### ISSUE THREAD

**Issue by neuecc** [msgpack/msgpack-cli#140]
I've generated `SerializerGenerator.GenerateSerializerCodeAssembly` from .NET MsgPack and reference to Unity's Project and load by Unity MsgPack-Full.

But Visual Studio shows following error in this line.

`var serializer = new MsgPack.Serialization.EmittingSerializers.Generated.ClassLibrary3_Class1Serializer(SerializationContext.Default);`

```
The type 'SerializationContext' is defined in an assembly that is not referenced. You must add a reference to assembly 'MsgPack, Version=0.6.0.0, Culture=neutral, PublicKeyToken=a2625990d5dc0167'
```

I tryed both .NET 3.5 project(DLL Runtime = .NET 2.0) and .NET 4.0 Project.

**Comment by yfakariya** [comment]
I asked him in offline, and he agreed to close this issue because this is not a problem now.
But it is welcome to open new issue related to this. Thank you for contribution.
