### ISSUE TITLE
bug in deserialaze

### ISSUE THREAD

**Issue by rasoulpoordelan** [msgpack/msgpack-cli#141]
when use unpack method in infinity loop my threads kill in c#

var serializer = SerializationContext.Default.GetSerializer<T>();
			Stream stream = new MemoryStream(data);
                       var result = serializer.Unpack(stream);

**Comment by yfakariya** [comment]
Sorry, it looks bug on `Unpacker` or generated serializer code even if the `data` was corrupted, but I need more information. Would you tell about your version of the msgpack, the contents of `data`, and the type(class) which you tried to deserialize?

**Comment by rasoulpoordelan** [comment]
Excuse me I use it for unpack
msg pack version 0.6.7

I use it in thread like this for unpack
when I use generic method it’s kill my thread 


Stream stream = new MemoryStream(data);
var result = MessagePackSerializer.Get<T>().Unpack(stream);
return result;


my class are
 
public class ResponseClass
	{
		public ResponseOptionsClass opts { get; set; }
		public object obj { get; set; }

		public string ToJson()
		{
			return Newtonsoft.Json.JsonConvert.SerializeObject(this);
		}
	}


public class ResponseOptionsClass
	{
		public short MessageId { get; set; }
		public string SessionId { get; set; }
		public int SqnNo { get; set; }
	}

**Comment by yfakariya** [comment]
Thank you for additional information. Types are seems to be usual except `object` typed field, so the failure should be triggered by the data. Could you give me the contents of the `data`, such as the result of `BitConverter.ToString(byte[])`?

**Comment by rasoulpoordelan** [comment]
my byte array
130,164,111,112,116,115,146,3,192,163,111,98,106,129,169,115,101,115,115,105,111,110,73,100,170,53,48,85,54,90,77,85,80,72,65

**Comment by yfakariya** [comment]
Thank you, but unfortunately I failed to reproduce the problem on my local environment. So, I'll be happy if you give extra information. I'm sorry to bother you.
* Would you tell me your runtime information? (OS, .NET/Mono/Unity version)
* Was it truly infinite loop? I guess it might be same as #118.
* If you can reproduce easily, would you tell me the call stack when it hanged?

**Comment by BehroozBahrameh** [comment]
We use .net 3.5 version
We have a thread and a timer with call back, In timer we user *pack* method like below in infinitive 30s interval:

    	var serializer = SerializationContext.Default.GetSerializer<T>();
	...
	serializer.Pack(stream, data);

Timer definition is :

    Timer t = new Timer(MyCallBack, null, 0, 2000);

and in the thread we have infinitive loop that by some condition we call *unpack* method like below :

    var result = MessagePackSerializer.Get<ResponseClass>().Unpack(stream);

Thread definition is :

    Thread readDataThread = new Thread(new ThreadStart(MyMethod));
    readDataThread.Start();

when unpack method calls in read, timer broken and after callback function dose not invoke, and show below messagein Output

    (CLR v4.0.30319: ....vshost.exe): Loaded 'MsgPack.Serialization.EmittingSerializers.GeneratedSerealizers0'. 
    (CLR v4.0.30319: ....vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_32\ISymWrapper\v4.0_4.0.0.0__b03f5f7f11d50a3a\ISymWrapper.dll'. Loading disabled by Include/Exclude setting.
    (CLR v4.0.30319: ....vshost.exe): Loaded 'MsgPack.Serialization.EmittingSerializers.GeneratedSerealizers1'. 
    (CLR v4.0.30319: ....vshost.exe): Loaded 'MsgPack.Serialization.EmittingSerializers.GeneratedSerealizers1.dll'. 
    (CLR v4.0.30319: ....vshost.exe): Loaded 'MsgPack.Serialization.EmittingSerializers.GeneratedSerealizers2'. 
    (CLR v4.0.30319: ....vshost.exe): Loaded 'Anonymously Hosted DynamicMethods Assembly'. 
    The thread 0x3200 has exited with code 259 (0x103).
    The thread 0x32e0 has exited with code 259 (0x103).
    The thread 0x332c has exited with code 259 (0x103).
    The thread 0x27a8 has exited with code 0 (0x0).

**Comment by yfakariya** [comment]
Thank you @BehroozBahrameh! However, I cannot convince the problem is infinite-loop(live locking), and I failed to reproduce the hung. I need callstack(stacktrace) when the thread hang to investigate the issue...
Although I failed to detect the cause of your issue, I found another cycle dead lock issue for serializer generation for complex type composition. So, did you use `T` for the timer thread which have reverse composition like following?
```C#
class A {
   public B B {get;set;}
}

class B {
  public A A {get; set;}
}
```

**Comment by BehroozBahrameh** [comment]
It's sample code that simulate problem :

    static void Main(string[] args)
    {
        MainProgram program = new MainProgram();
        program.Init();
    }

and MainProgram class is :

    public class ResponseClass
    {
        public ResponseOptionsClass opts { get; set; }
        public object obj { get; set; }
    }

    public class ResponseOptionsClass
    {
        public short MessageId { get; set; }
        public string SessionId { get; set; }
        public int SqnNo { get; set; }
    }

	public class MainProgram
    {
    	public void Init()
    	{
    		Timer t = new Timer(TimerCallBack, null, 0, 2000);
    
    		Thread readDataThread = new Thread(new ThreadStart(ReadData));
    		readDataThread.Start();
    	}
    
    	private void TimerCallBack(Object myObj)
    	{
    		Debug.WriteLine("******* CALLBACK");
    		//PACK
    		var serializer = SerializationContext.Default.GetSerializer<ResponseClass>();
    		var stream = new MemoryStream();
    		serializer.Pack(stream, new ResponseClass
    		{
    			opts = new ResponseOptionsClass
    			{
    				MessageId = 1
    			},
    			obj = null
    		});
    	}
    
    	public void ReadData()
    	{
    		var i = 0;
    
    		while (true)
    		{
    			if (++i == 1000000000)
    			{
    				i = 0;
    				Debug.WriteLine("******** LOOP");
    
    				var data = new byte[] { 146, 192, 147, 1, 192, 0 };
    
    				var serializer = SerializationContext.Default.GetSerializer<ResponseClass>();
    				Stream stream = new MemoryStream(data);
    				var obj = serializer.Unpack(stream);
    			}
    		}
    	}
    }

in ResponseClass class if comment opts property, you can see CALLBACK log each second, but when exists any property of type class timer dose not work.

**Comment by yfakariya** [comment]
Thank you. I'll try this night.

**Comment by yfakariya** [comment]
I tried reproduce in 3 weeks intermittently, it worked with about 1 million log lines. I need more info to solve this issue.

**Comment by yfakariya** [comment]
Close because no additional post about 2 months. It is welcome to reopen when any new facts are found.
