### ISSUE TITLE
bug in unpack

### ISSUE THREAD

**Issue by rasoulpoordelan** [msgpack/msgpack-cli#142]
when use unpack method in infinity loop my threads kill in c#

var serializer = SerializationContext.Default.GetSerializer<T>();
			Stream stream = new MemoryStream(data);
                       var result = serializer.Unpack(stream);

**Comment by yfakariya** [comment]
@rasoulpoordelan Is this duplicated with #141?

**Comment by yfakariya** [comment]
Close because this looks duplicated.
