### ISSUE TITLE
Add support for the IgnoreDataMember attribute

### ISSUE THREAD

**Issue by antwilliams** [msgpack/msgpack-cli#146]
I am investigating using MsgPack for some new serialisation requirements in our application, we currently use JSON but need something a little less verbose! 
Our current class hierarchy uses the IgnoreDataMember attribute to indicate which properties to skip during serialisation, unfortunately it seems that MsgPack-Cli only uses the NonSerialized attribute which can't be applied to properties (issue #55).

It would be quite an undertaking to decorate all of our classes with the MessagePackIgnoreAttribute and it would introduce an additional dependency on some of our assemblies that we're trying to avoid.

Is it possible to add support for ignoring properties decorated with the IgnoreDataMember attribute? It is defined in a different assembly but as [far as I can see](https://msdn.microsoft.com/en-us/library/system.runtime.serialization.ignoredatamemberattribute(v=vs.110).aspx#Anchor_7) it is supported across all Windows NET distributions (Silverlight, Portable etc) and in Mono.

I am happy to make the modifications and submit a pull request, although it seems to be a one line change in SerializationTarget.cs and probably easier for you to do since I don't have the full test environment configured.

Thanks,
Anthony

**Comment by yfakariya** [comment]
Sorry for delay, but could you use `MessagePackIgnore` instead?

**Comment by yfakariya** [comment]
This issue should be solved in 0.7.
Feel free to reopen if you find any issues.

**Comment by antwilliams** [comment]
Thanks for adding this @yfakariya. I'll let you know if I have any issues.
Sorry I didn't respond to your question back in March, I don't use GitHub very often and missed the notification!
MessagePackIgnore wasn't an option unfortunately since I was working with some third party classes where I couldn't add references.
