### ISSUE TITLE
An explicit implemented IPackable causes MethodAccessException

### ISSUE THREAD

**Issue by CnSimonChan** [msgpack/msgpack-cli#150]
I'm targeting Desktop .NET Framework 4.6.1 (4.5.0 also tested with same result), I have a class explicit implements `IPackable` and `IUnpackable`, but serialization causes `MethodAccessException`:  

Attempt by method 'MsgPack.Serialization.EmittingSerializers.Generated.Tests_LiveDetailIdsSerializer1.UnpackFromCore(MsgPack.Unpacker)' to access method 'Tests.LiveDetailIds.MsgPack.IUnpackable.UnpackFromMessage(MsgPack.Unpacker)' failed.

I'm not familiar with .NET security, but seems the call to `typeof( TObject ).GetInterfaceMap( typeof( IUnpackable ) ).TargetMethods.Single()` at [SerializerBuilder`3.Object.cs L232](https://github.com/msgpack/msgpack-cli/blob/master/src/MsgPack/Serialization/AbstractSerializers/SerializerBuilder%603.Object.cs#L232) got a `NonPublic` method that needs to be fully trusted to call by generated assemblies.

I tried to replace that with `typeof( IUnpackable ).GetMethod( "UnpackFromMessage" )` which returns a `Public` `MethodInfo` and can fix my issue.

Same to `IPackable`. 

Another problem: when a class derived from `List<T>` implements `IPackable` and `IUnpackable`, MsgPack will serialize it as an array but ignore `IPackable`.

**Comment by yfakariya** [comment]
Thank you for reporting.
* `MethodAccessException` should be caused because of lack of casting to the interface. This is a bug, so I'll fix it.
* Currently, `IPackable` and `IUnpackable` only works types which do not implement `IEnumerable`. I think design change of this needs more consideration and discussion. Do you really have problem for this?

**Comment by CnSimonChan** [comment]
My class derived from `List<T>` and implemented `IPackable`/`IUnpackable` at the beginning, because the serialized object is a Map with numeric key so I want to convert it to a list. The result is MsgPack keeps throwing exceptions saying the stream doesn't contains an array, and I found that breakpoints inside `UnpackFromMessage()` are never hit, so I quickly realized the priority of `List<T>` is higher than `IUnpackable` and edited my class.

But I think it's unreasonable, `IPackable`/`IUnpackable` is a more advanced feature so when users implement them, they must want to override the default behavior, they want a list that is not a list, or an object that is not an object.

**Comment by yfakariya** [comment]
You are right. I'll support with compatibility switch as another issue for it.

**Comment by yfakariya** [comment]
This issue was fixed in 0.7.0-alpha3, so I've closed it.
