### ISSUE TITLE
 public Action<int> GiveMoney;

### ISSUE THREAD

**Issue by nanddonet** [msgpack/msgpack-cli#154]
I have a property inside a class like:

 `public Action<int> GiveMoney;`

in a class called Bank

When calling

` var serializer = MsgPack.Serialization.SerializationContext.Default.GetSerializer<Bank>();`

It yields an exception

> This operation is not supported because 'System.Reflection.MethodInfo' cannot be instanciated.

I don´t want to serialize an Action just the properties. how could I do that? regards.

**Comment by yfakariya** [comment]
Marking the property with `[MessagePackIgnore]` should help you.

**Comment by nanddonet** [comment]
@yfakariya it worked, thank you so much for the quick answer!

**Comment by yfakariya** [comment]
I've closed because it looks solved.
