### ISSUE TITLE
[Question]When using messagepackmemeber attribute, redundant data appended in my case.  

### ISSUE THREAD

**Issue by naotakat** [msgpack/msgpack-cli#158]
In case of inheriting base class like below

My Base Class
public class A { // added new property in future
 [MessagePackMember(0)]
 int a;
 [MessagePackMember(1)]
 int b;
 [MessagePackMember(2)]
 int c;
}

Inherited Class
public class B {
 [MessagePackMember(10)]
 int a1;
 [MessagePackMember(11)]
 int b1;
 [MessagePackMember(12)]
 int c1;
}

After generating serializer of above b class, it seems to have null data between member 3 ~ 9 not used.
it can be redundant data. so packet data size is going to be increased. 
how can I avoid to have redundant data?

**Comment by yfakariya** [comment]
It is by design. The number of `[MessagePackMember]` specifies 'index' of serialized array.
You can avoid this problem with `SerializationMethod.Map`. There are no smart solutions to resolve inheritance yet.

**Comment by naotakat** [comment]
I'll use Map despite drawbacks. 
Thank you.
