### ISSUE TITLE
Custom Message Pack Serializer

### ISSUE THREAD

**Issue by lethanhbk55** [msgpack/msgpack-cli#160]
I try to port my Message Pack Template from Java to C#
here is Java code
```
@Override
public Object read(Unpacker unpacker, Object result, boolean required) throws IOException {
    Object _result = null;
    ValueType nextValueType = unpacker.getNextType();
    switch (nextValueType) {
    case NIL:
        unpacker.readNil();
        _result = null;
        break;
    case ARRAY:
        _result = this.readList(unpacker, required);
        break;
    case MAP:
        _result = this.readMap(unpacker, required);
        break;
    case BOOLEAN:
        _result = unpacker.readBoolean();
        break;
    case FLOAT:
        try {
            _result = unpacker.readFloat();
        } catch (MessageTypeException e) {
            _result = unpacker.readDouble();
        }
        break;
    case INTEGER:
        try {
            _result = unpacker.readInt();
        } catch (MessageTypeException e) {
            _result = unpacker.readLong();
        }
        break;
    case RAW:
        RawValue value = (RawValue) unpacker.readValue();
        _result = value.getByteArray();
        break;
    default:
        throw new RuntimeException("Value type is not supported or invalid: " + nextValueType);
    }
    return _result;
}
```

And mgspack-cli(C#) I not found equivalent method getNextType(), readNil() from Unpacker. What show I do now?

```
protected override object UnpackFromCore(Unpacker unpacker)
    {
        Object result = null;

        //what should i do

        return result;
    }
```

**Comment by yfakariya** [comment]
1. The nil has been already handled by base class, so you don't have to care about.
2. At begining of the `UnpackFromCore`, the unpacker has the read value in `LastReadData` property(it represents the count of array items in most cases), and it will be updated in next `Read()` call. Then, you will get `MessagePackObject` value, and it has `IsTypeOf(Type)` and various `As...` methods to get actual value. Unfotunatelly, there are no equivalents of `getNextType()` which returns 'can be placed in switch' value.

If you want to implement unpacker logic manually, you want to use `SerializerGenerator` or its wrapper cli tool named `mpu.exe`, because they can generate auto-generated unpacker source code in C#.

**Comment by lethanhbk55** [comment]
I create my custom serializer above:
` public class GenericTypeTemplate : MessagePackSerializer<object>
    {
        protected override void PackToCore(Packer packer, object obj)
        {
            if (obj == null)
            {
                packer.PackNull();
            }
            else if (obj.GetType().Name == "Byte[]")
            {
                packer.PackRaw((byte[])obj);
            }
            else if (PrimitiveTypeUtils.isPrimitiveTypeOrWrapperType(obj.GetType()))
            {
                packer.Pack(obj);
            }
            else if (ArrayUtils.IsArrayOrCollection(obj.GetType()))
            {
                writeList(packer, obj);
            }
            else if (obj.GetType().IsAssignableFrom(typeof(IDictionary<string, object>)))
            {
                IDictionary<string, object> map = (IDictionary<string, object>)obj;
                packer.PackMapHeader(map.Count);
                foreach (KeyValuePair<string, object> entry in map)
                {
                    packer.PackString(entry.Key);
                    PackToCore(packer, entry.Value);
                }
            }
        }

        protected void writeList(Packer packer, object arrayOrCollection)
        {
            packer.PackArrayHeader(ArrayUtils.Length(arrayOrCollection));
            ArrayUtils.ForEach(arrayOrCollection, (obj) =>
            {
                PackToCore(packer, obj);
            });
        }

        protected override object UnpackFromCore(Unpacker unpacker)
        {
            Object result = null;
            MessagePackObject obj = unpacker.LastReadData;
            if (obj.IsNil)
            {
                return null;
            }
            else if (obj.IsArray)
            {
                result = readList(unpacker);
            }
            else if (obj.IsMap)
            {
                result = readMap(unpacker);
            }
            else if (obj.IsRaw)
            {
                result = obj.AsBinary();
            }
            else
            {
                unpacker.Read();
                result = unpacker.Data.Value;
            }
                        
            return result;
        }

        private object readList(Unpacker unpacker)
        {
            long length = 0;
            IList<object> list = new List<object>();
            unpacker.ReadArrayLength(out length);
            for (int i = 0; i < length; i++)
            {
                list.Add(UnpackFromCore(unpacker));
            }
            return list;
        }

        protected object readMap(Unpacker unpacker)
        {
            IDictionary<string, object> map = new Dictionary<string, object>();
            long size = 0;
            unpacker.ReadMapLength(out size);
            for (int i = 0; i < size; i++)
            {
                string key = "";
                unpacker.ReadString(out key);
                object value = UnpackFromCore(unpacker);
                map[key] = value;
            }
            return map;
        }
    }`

How to user my custom serializer when I create `GenericTypeTemplate template = new GenericTypeTemplate();` It throws an AgumentException and more help me check UnpackForCore (C#) logic code has run like Java code?
