### ISSUE TITLE
Field & property overriding

### ISSUE THREAD

**Issue by Roman-Blinkov** [msgpack/msgpack-cli#162]
Hi!
I found issue caused by field & property overriding and wrote simple workaround 
[ Code to reproduce issue ] ( https://github.com/Roman-Blinkov/msgpack-cli/blob/008c5c28dd16d14e232266de0fabe01df04f7c1e/test/MsgPack.UnitTest/InheritanceTest.cs ) 
[ Issue fix proposal ] ( https://github.com/Roman-Blinkov/msgpack-cli/commit/008c5c28dd16d14e232266de0fabe01df04f7c1e )
Check #161, please.

**Comment by yfakariya** [comment]
Thank you! I merged your request with trivial fixes.
