### ISSUE TITLE
I couldn't build 0.7 alpha3

### ISSUE THREAD

**Issue by naotakat** [msgpack/msgpack-cli#163]
Hello

Thank you for improving so much.
I tried to build this version on windows 10 and VS2015. but I couldn't.

Error Messages like below
> C:\Program Files (x86)\MSBuild\Microsoft\NuGet\Microsoft.NuGet.targets(140,5): error : Your project.json doesn't have a runtimes section. You should add '"runtimes": { "win": { } }' to your project.json and then re-run NuGet restore.

I googled and found msbuild issue.
[https://github.com/Microsoft/msbuild/issues/394](#394)

How should I solve this?

Thank you

Nao

**Comment by naotakat** [comment]
@yfakariya 

After adding "runtimes" , I can build with some warnings.
Is it right solution?

**Comment by yfakariya** [comment]
Which project do you see above error?

**Comment by naotakat** [comment]
msgpack(4.6) it is

**Comment by yfakariya** [comment]
OK, this is caused by trushes for previous .NET Core build items(project.json and xproj). 
# Actually, I've not opened from VS2015 for that project.
Try pull latest branch, unload msgpack project, reload it, and then build.
Thank you for reporting!

**Comment by naotakat** [comment]
Thank you for fixing. 
I've just confirmed.
