### ISSUE TITLE
System.Runtime.CompileService in MsgPack unity full 

### ISSUE THREAD

**Issue by naotakat** [msgpack/msgpack-cli#164]
I would like to use compiled dll for unity on .net 4.6 framework.
That is why it is for convenience on using for client and server.
In 0.7.0 alpha3, I couldn't run with unity full dll on my server (.net 4.6.1).
because of duplicating name of namespace System.Runtime.CompileService.CallerMemberName in MsgPack unity full and mscorlib(4.0.0).
I looked for why it exists.
It was to use for trace. 
Why don't  it have a different name?

**Comment by yfakariya** [comment]
Thank you for reporting. This is compilation bug.

**Comment by yfakariya** [comment]
I understand `System.Runtime.CompilerServices.CallerMemberName` is required to enable C#'s caller info feature in old runtime. It is reason to use same attribute name.

If you want to build Unity.Full for .NET 4, you can just comment out the attribute definition code.

I'll consider opt out code when "TRACING" compiler directive is off.

**Comment by naotakat** [comment]
Thank you for replying and temporary solution.

I am going to comment out.

Thank you.
