### ISSUE TITLE
Does MSGPACK support polymorphism, looking at documentation it seems yes, but it's not working with practical c#.net application. 

### ISSUE THREAD

**Issue by gaurav-pra** [msgpack/msgpack-cli#165]
I've following interface / class structure :-

```
public interface IRule
 {
        string RuleType { get; set; }
        bool GetStatus();
}
```

    public class TimeRule : IRule
    {
        public DateTime Time { get; set; }

        public bool GetStatus()
        {
            throw new NotImplementedException();
        }

        public string RuleType { get; set; }
    }
```

```
```
public class ProcessStateRule : IRule
    {
        public long ProcessStateId { get; set; }
        public bool GetStatus()
        {
            throw new NotImplementedException();
        }

        public string RuleType { get; set; }
    }

```

```
public class Rules
    {
        public Rules()
        {
            this.RuleCollection = new List<IRule>{
                                    new TimeRule{ RuleType = "TimeRule", Time = DateTime.Now},
                                    new ProcessStateRule { RuleType = "ProcessStateRule", ProcessStateId = 100 }
                        };
        }

        public IList<IRule> RuleCollection { get; set; }
    }

```

I'm trying to serialize Rules class default object with following code but below code raising exception while creating serializer object, it says "This operation is not supported because 'IRule' can not be instantiated' . 

            Rules rules = new Rules();        
            var stream = new MemoryStream();
            var serializer = MessagePackSerializer.Get<Rules>();
            serializer.Pack(stream, rules);

Moreover, this is also not fixed by applying MessagePackKnownTypeAttribute on RuleCollection property in Rules class.

Could anybody help me on this.

**Comment by yfakariya** [comment]
Marking collection typed property with `[MessagePackKnownType]` represents "this collection should be polymorphic" rather than "ITEMS of this collection should be polymorphic". So, use `[MessagePackKnownCollectionItemType]` instead as following:
```csharp
public class Rules
{
    public Rules()
    {
        this.RuleCollection = new List<IRule>{
                                  new TimeRule{ RuleType = "TimeRule", Time = DateTime.Now},
                                  new ProcessStateRule { RuleType = "ProcessStateRule", ProcessStateId = 100 }
                              };
    }

    [MessagePackKnownCollectionItemType( "Time", typeof( TimeRule ) )]
    [MessagePackKnownCollectionItemType( "ProcessStatus", typeof( ProcessStateRule ) )]
    public IList<IRule> RuleCollection { get; set; }
}
```

**Comment by gaurav-pra** [comment]
Thanks Yusuke for your quick response. It works as you suggested.
