### ISSUE TITLE
IL2CPP Status

### ISSUE THREAD

**Issue by awdogsgo2heaven** [msgpack/msgpack-cli#172]
The wiki seems to act its not supported yet, but I do see clear references to people trying to use it in some issues, where was this left off at? Does it partially work? is there some important missing features?

**Comment by yfakariya** [comment]
Sorry I am delay to update wiki. IL2CPP IS ONLY supported from 0.7.0.

**Comment by yfakariya** [comment]
Closed because it is no response for answer. It is welcome to reopen for further question. Thank you for contribution.
