### ISSUE TITLE
Can I use lowerCamelCase when serialize a map? 

### ISSUE THREAD

**Issue by JackBao** [msgpack/msgpack-cli#175]
Can I use lowerCamelCase when serialize a map?  thanks

**Comment by yfakariya** [comment]
Currently, you must use `MessagePackMemberAttribute` for every members. 
I think you don't want to do so, aren't you? If so, I will add options to customize key casings.

**Comment by JackBao** [comment]
Add an option would be great, otherwise all my clients need to be updated to use PascalCase, do we have a schedule for this?

**Comment by yfakariya** [comment]
No, I don't have specific plan for it, but there are no reason to leave this issue open. Do you have any request for this? I want to add with #136 as map related enhancements.

**Comment by JackBao** [comment]
Great! I found this enhancement is in develop, when will this feature release?

**Comment by yfakariya** [comment]
I will release in few week(s) with Xamarin related packing issue.
