### ISSUE TITLE
.Net Framework Versions

### ISSUE THREAD

**Issue by mathrb** [msgpack/msgpack-cli#176]
Hello,
It seems strange that a .Net 4.5 project uses the .Net 3.5 - client version of the msgpack, because it cannot use .Net 4.5.2
After cloning the repo, changing the target framework to 4.5 is ok, no compilation error.
Maybe you could provide more .net framework versions in nuget repo ?
My issue was that a Tuple<Dictionary<string,object>,string,List<object>> (thanks to zerorpc :p ) does not have a default constructor in .Net 3.5 client. But it works in .Net 4.5(didn't try with .Net 4)

**Comment by yfakariya** [comment]
Thank yoy for feedback. My decision (cutting off unsupported old frameworks) was too rough. I will restore 4.5 and 4.6 in few days.

**Comment by yfakariya** [comment]
Sorry for delay. I fixed this issue last week with 0.7.1.

**Comment by mathrb** [comment]
Thanks
