### ISSUE TITLE
Nuget restore issue with v0.7.0

### ISSUE THREAD

**Issue by calloncampbell** [msgpack/msgpack-cli#177]
We get the following nuget restore issue in TeamCity with the latest v0.7.0 build. We downgraded to v0.6.8 and issue goes away.

> [11:38:11][Step 2/4] restore: Restoring NuGet packages for Plato.NET.sln (1s)
> [11:38:11][restore] NuGet command: C:\BuildAgent\plugins\nuget-agent\bin\JetBrains.TeamCity.NuGetRunner.exe C:\BuildAgent\tools\NuGet.CommandLine.DEFAULT\tools\NuGet.exe restore C:\BuildAgent\work\cfb932647685dff1\Plato.NET.sln
> [11:38:11][restore] Starting: C:\BuildAgent\temp\agentTmp\custom_script6315179492532981544.cmd
> [11:38:11][restore] in directory: C:\BuildAgent\work\cfb932647685dff1
> [11:38:11][restore] JetBrains TeamCity NuGet Runner 8.0.37573.9
> [11:38:11][restore] Registered additional extensions from paths: C:\BuildAgent\plugins\nuget-agent\bin\plugins-2.8
> [11:38:11][restore] Starting NuGet.exe 2.8.60717.93 from C:\BuildAgent\tools\NuGet.CommandLine.DEFAULT\tools\NuGet.exe
> [11:38:12][restore] WARNING: 'MsgPack.Cli' already has a dependency defined for 'System.Collections'.
> [11:38:12][restore] Installing 'MsgPack.Cli 0.7.0'.
> [11:38:13][restore] 'MsgPack.Cli' already has a dependency defined for 'System.Collections'.
> [11:38:13][restore] Process exited with code 1

Oddly enough NuGet restore seems fine with Visual Studio and Command line.

**Comment by kryptt** [comment]
I have a similar issue myself. 

It seems dependencies have come in that make the project incompatible with Xamarin ?

**Comment by yfakariya** [comment]
It looks package dependency resolution problem. Could you give `packages.config` and/or `project.config` used? I might fix it if this issue is not TeamCity implementation specific.

**Comment by rfcdejong** [comment]
I get this error in the commandline in visual studio 2013 using the Package Manager Console. .NET 4.6.1

PM> Install-Package MsgPack.Cli
Install-Package : 'MsgPack.Cli' already has a dependency defined for 'System.Collections'.
At line:1 char:1
+ Install-Package MsgPack.Cli
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand

**Comment by yfakariya** [comment]
Thank you @rfcdejong! I will investigate it with your information.

**Comment by yfakariya** [comment]
I reproduced this issue and I found that this is caused by nuget version. Indeed, NuGet 2.x does not support .NET Standard, which is added in 0.7.0 package, so they cannot handle package correctly. When I update nuget in VS2013 to 2.12, In fact, I could install msgpack package correctly.

So, these are solution:
* If you use VS2013(or before), please update your NuGet 2.12 or later.
* If you use TeamCity, please update your TeamCity or contact to support to use latest NuGet (2.12 or 3.x) compatible feature.
* To prevent confusing error message, I've added `minClientVersion` to `.nuspec` file (it is nuspec bug -- I missed it).

Thanks.

**Comment by yfakariya** [comment]
I've released modified version as 0.9.0-beta1. Would you try it in Team City environment?

**Comment by yfakariya** [comment]
Close because it looks nupkg issue and solved.
