### ISSUE TITLE
Cannot reference monotouch.dll in a Xamarin.iOS project

### ISSUE THREAD

**Issue by JFMG** [msgpack/msgpack-cli#181]
The update to MsgPack.Cli 0.7.1 lead to the following error:

> Severity	Code	Description	Project	File	Line	Suppression State
Error		Cannot reference 'monotouch.dll' in a Xamarin.iOS project - it is implicitly referenced by 'MsgPack, Version=0.7.0.0, Culture=neutral, PublicKeyToken=a2625990d5dc0167'.	MyCompany.Mobile.MyApp.iOS	C:\Program Files (x86)\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets	681	

Is there any way to fix it? Otherwise we go down again to version 0.6.8

**Comment by yfakariya** [comment]
It looks MsgPack.Xamarin.iOS [build issue about unitifie API](https://developer.xamarin.com/guides/cross-platform/macios/unified/updating-tips/) although I wonder if the 0.6.8 worked because I did not change it dependencies. I'll release 0.8 beta in few days, so could you try it?

**Comment by yfakariya** [comment]
I found `[assembly:MonoTouch.Foundation.LinkerSafe]` shoud cause this error.

**Comment by yfakariya** [comment]
@JFMG Could you try this nightly package? https://ci.appveyor.com/project/yfakariya/msgpack-cli-x2p85/build/master-46/artifacts

**Comment by JFMG** [comment]
Thanks @yfakariya It works! 👍

**Comment by yfakariya** [comment]
Thank you. I'll release as 0.8 beta soon, and will 0.8 final if it does not have problems after a week.

**Comment by JFMG** [comment]
Awesome :-)

**Comment by yfakariya** [comment]
Close because this should be solved in 0.8.
