### ISSUE TITLE
camelCase transformations in object

### ISSUE THREAD

**Issue by alittletina** [msgpack/msgpack-cli#183]
Hi,

I'd like to transform object property names to camelCase during serialization (and the reverse during deserialization). So if an object has the property `IsInvalid`, I'd like it to be serialized as `isInvalid` for interopability.

Currently for example, if a C# property is PascalCase and we try to deserialize in Java with camelCase (and no attributes), it won't work.

Is there a functionality to do that?

Thank you so much!

**Comment by yfakariya** [comment]
As of 0.8, `SerializationContext.DictionarySerializationOptions.KeyTransformer` exists for it.

**Comment by alittletina** [comment]
Ohh, brilliant! Thank you! ^^

So the dictionary serialization options apply for any dictionary-like thing, including statically typed C# objects?

**Comment by alittletina** [comment]
I have one more question: is there a similar option for changing the case of enum names when using `EnumSerializationMethod.ByName`?

**Comment by yfakariya** [comment]
No, I forgot it. Would you submit another issue for enum?
