### ISSUE TITLE
Can the msgpack serialize JObject object?

### ISSUE THREAD

**Issue by SpiderShrimp888** [msgpack/msgpack-cli#188]
I tried...throwed a exception says that Jtoken can not be  instanciated...
How can I solve it?

**Comment by yfakariya** [comment]
Implementing own custom serializer, or trying 0.9 beta which allows asymmetric (pack only) serializer

**Comment by SpiderShrimp888** [comment]
3ks bro

**Comment by SpiderShrimp888** [comment]
tks,bro.
