### ISSUE TITLE
Option for reflection serializers

### ISSUE THREAD

**Issue by samcragg** [msgpack/msgpack-cli#192]
During startup of our client, a fair amount of time is spent by MsgPack generating the serializers. Unfortunately, some of that time it's generating serializers for types that will only be deserialized once. Playing around with the code and if I change the SerializerOptions.EmmitterFlavor to ReflectionBased (ironically I'm doing this via reflection) we get a lot of speed up.

Would you accept a PR that adds a bool property to the SerializerOptions to disable dynamic code being emitted, maybe called DisableCodeEmit, that sets the internal property as required (and no effect if the platform doesn't support it)?

**Comment by yfakariya** [comment]
It is nice idea! The only reason to not exposed this option is "do not expose API when someone really want it".
But I think `DisableRuntimeCodeGeneration` is better naming. How do you feel it?

**Comment by samcragg** [comment]
Sounds a good name to me - I'm happy to submit a PR tomorrow if you like or if you think it's a trivial change and want to do it yourself I won't be offended :)

There's no major rush by the way, I've got a work around in place.

**Comment by yfakariya** [comment]
Let's push it :)
