### ISSUE TITLE
what's the different between unity with unity-full in the MsgPack.Cli.0.9.0-beta1 ?

### ISSUE THREAD

**Issue by indie21** [msgpack/msgpack-cli#195]
which should I choose?

**Comment by yfakariya** [comment]
If you use 'corlib only' build in Unity player settings, use unity/ build. Otherwise, use unity-full/ which depends on System.dll assembly and supports Stack<T> and Queue<T> serialization.

**Comment by yfakariya** [comment]
Close this question because it was answered about half year ago.
