### ISSUE TITLE
MessagePackSerializer<object> does not use registered custom serializers

### ISSUE THREAD

**Issue by aidin36** [msgpack/msgpack-cli#197]
Assume the following code. If I put a breakpoint in PackToCore, it will never get hit.

But if instead of `context.GetSerializer<object>()`, I write `context.GetSerializer<IData>()`, it would be fine.

The real-world problem I have is as follow: I have a `Dictionary<string, object>` to serialize. Type of Values can be either a primitive type, or a specific interface. My custom `MessagePackSerializer` knows how to serialize that interface. But because of the behavior I explained, I couldn't successed in serializing the dictionary.

``` C#
using System;
using System.Collections.Generic;
using MsgPack.Serialization;

namespace BugReport
{
    public class IData
    {
    }

    public class BaseData : IData
    {
        public int DataField { get; set; }
    }

    public class ChildData : BaseData
    {
    }

    public class DataSerializer : MessagePackSerializer<IData>
    {
        public DataSerializer(SerializationContext ownerContext)
            : base(ownerContext)
        {
        }

        protected override void PackToCore(MsgPack.Packer packer, IData objectTree)
        {
            throw new NotImplementedException();
        }

        protected override IData UnpackFromCore(MsgPack.Unpacker unpacker)
        {
            throw new NotImplementedException();
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            SerializationContext context = new SerializationContext();
            
            context.Serializers.Register<IData>(new DataSerializer(context));

            ChildData actualData = new ChildData();

            MsgPack.Serialization.MessagePackSerializer serializer = context.GetSerializer<object>();

            byte[] serialized = serializer.PackSingleObject(actualData);
            object recoveredData = serializer.UnpackSingleObject(serialized);
        }
    }
}
```

**Comment by yfakariya** [comment]
Sorry for delay, I think you have to supply `PolymorhicSchema` in an argument of `SerializationContext.GetSerializer`. This becomes public API now, and sample is [here](https://github.com/msgpack/msgpack-cli/blob/master/samples/Samples/Sample08_Polymorphism.cs#L84).

**Comment by yfakariya** [comment]
Close this question because it was answered about half year ago.
