### ISSUE TITLE
Installing MsgPack Nuget for UWP App References libc.dll; Store upload fails

### ISSUE THREAD

**Issue by JSalazar88** [msgpack/msgpack-cli#206]
Somewhat similar to Issue #41, we are seeing that installing MsgPack.Cli from Nuget, for a UWP project, results in a dependency on libc.dll. This prevents projects including MsgPack from being capable of Windows Store upload, as compiling with the .NET Native toolchain will fail.

However, compiling the MsgPack source directly DOES result in a MsgPack.dll (Uwp project) which does NOT depend on libc.dll. Perhaps the Nuspec file needs to be updated so that installing via Nuget does not break the UWP store build (thus preventing Store upload)?

Thanks!

**Comment by yfakariya** [comment]
It is mistake when I introduce .NET Standard. I will fix this. Sorry.

**Comment by JSalazar88** [comment]
Thank you! Could you let me know which Nuget version it is fixed in once you fix it!?! Many thanks.
