### ISSUE TITLE
Does msgpack-cli support asp.net?

### ISSUE THREAD

**Issue by platstar** [msgpack/msgpack-cli#209]
I have sliven this issue just now, because I use the old version from NuGet , download the 0.9 version to fix it.

**Comment by yfakariya** [comment]
Of course, asp.net is supported!

It looks build or its configuration related error, but it could happen if packaging bug of msgpack exists.
Would you show me full project for repro? 
Thanks.

**Comment by yfakariya** [comment]
I see.
