### ISSUE TITLE
Does double serialization supports BigEndian environment?

### ISSUE THREAD

**Issue by neuecc** [msgpack/msgpack-cli#213]
I've read packing double code.
Pack `single` code has branches by IsLittleEndian but pack `double` code has not.
https://github.com/msgpack/msgpack-cli/blob/master/src/MsgPack/Packer.Packing.cs#L1108-L1123
Does this support BigEndian?

**Comment by yfakariya** [comment]
Yes. For `Single`, I implemented encoding using pointer operation effectively, so it is required to reverse the order when it runs on little endian machine. In oposite, other numerics, including `Double`, use shift operator which abstracts endian.

**Comment by neuecc** [comment]
Thank you and sorry, I've missed shift operator(sorry for no consideration question).
