### ISSUE TITLE
Re-serialize a MessagePackObject?

### ISSUE THREAD

**Issue by endel** [msgpack/msgpack-cli#234]
Hi there,

Given that I have a `MessagePackObject` instance, I'd like to have a `byte[]` of its representation. 

I basically want to re-serialize the de-serialized object back to `byte[]`. 

**My failed attempt:**

```
MessagePackObject myObj = ....; // unpacked object
var serializer = MessagePackSerializer.Get<byte[]>();
byte[] packedAgain = serializer.PackSingleObject( myObj );
```

**Error message:**

```
ArgumentException: 'MsgPack.MessagePackObject' is not compatible for 'System.Byte[]'.
Parameter name: objectTree
MsgPack.Serialization.MessagePackSerializer`1[System.Byte[]].ThrowArgumentException (System.String message, System.String parameterName)
MsgPack.Serialization.MessagePackSerializer`1[System.Byte[]].InternalPackSingleObject (System.Object objectTree)
MsgPack.Serialization.MessagePackSerializer.PackSingleObject (System.Object objectTree)
```

This is very simple to achieve in JavaScript. (`msgpack.encode( msgpack.decode( packedMessage ) )`)

Thanks in advance.

**Comment by yfakariya** [comment]
Use `MessagePackSerializer.Get<MessagePackObject>()` instead. 

`MessagePackSerializer.PackSingleObject(object)` is just a non generic wrapper for `PackSingleObject(T)`.

**Comment by endel** [comment]
Thank you so much for your swift reply @yfakariya, as always! 🎉
