### ISSUE TITLE
extension types support

### ISSUE THREAD

**Issue by schmurfy** [msgpack/msgpack-cli#244]
I am currently trying to reimplement an existing messagepack base protocol but I need extension types for a specific application type, looking at the sources I don't find any support for these types, only a mention of adding "PackerUnpackerExtensinos" in the changelog which does not exists anywhere as far as I can tell...

Was it supported and dropped ? Or did I miss something and it is currently supported by another means ?

**Comment by yfakariya** [comment]
Currently ext type is only supported via `MessagePackExtendedTypeObject` and you must write custom serializer to map between ext type and .NET type. `PackerUnpackerExtensions` just have extensions methods of `Packer` and `Unpacker`.

**Comment by schmurfy** [comment]
I ended up using another library.
