### ISSUE TITLE
custom serializer not used

### ISSUE THREAD

**Issue by schmurfy** [msgpack/msgpack-cli#245]
I am serializing an object containing various fields and one of them is an object for which I defined a special serializer but it is not called, is it expected ?

Here is the class of the object I serialize:
```
  public class Message
  {
    public string Type;
    public Int32 Id;
    public string ServiceName;
    public string MethodName;
    public object[] Arguments;
  }
```

Arguments can contains various types, one of them is an object with a special serializer, if I serialize it directly the serializer is correctly, if I my object class instead of `object[]` it also works but in my case I can't do that, Arguments may contains `[0, "one"]` and it is perfectly valid.

Can I make the library look the real class and not stop at the defined container type ?

**Comment by schmurfy** [comment]
I tried using the ResolveSerializer event but it raises an error if I return a serializer for my specific class while it tries to pack an `object` :(

**Comment by yfakariya** [comment]
Sorry for delayed response. Did you set the serializer instance to the `SerializationContext` instance via its `Register` method as following?

```csharp
var context = /* your serialization context or SerializationContext.Default */;
context.Serializers.Register<Message>(new YourCustomSerializer());
```

**Comment by schmurfy** [comment]
I ended up using another library.
