### ISSUE TITLE
Support for cyclic references?

### ISSUE THREAD

**Issue by JulianMay** [msgpack/msgpack-cli#248]
Hi
At first I thought there was a cyclic reference, but there is not... The stacktrace looks like this:

- Message: "Arithmetic operation resulted in an overflow."
- Source: "MessagePack" 
- StackTrace:
- - at MessagePack.MessagePackBinary.WriteString(Byte[]& bytes, Int32 offset, String value)
- - at MessagePack.Formatters.GuidFormatter.Serialize(Byte[]& bytes, Int32 offset, Guid value, IFormatterResolver formatterResolver)
- - at MessagePack.Formatters.Ajour_Subscriptions_Projections_RegistrationSearch_Models_RegistrationFormatter.Serialize(Byte[]& , Int32 , Registration , IFormatterResolver )
- - at MessagePack.Formatters.DictionaryFormatterBase´5.Serialize(Byte[]& bytes, Int32 offset, TDictionary value, IFormatterResolver formatterResolver)
- - at MessagePack.Formatters.Ajour_Subscriptions_Projections_RegistrationSearch_Models_ProjectionModelFormatter.Serialize(Byte[]& , Int32 , ProjectionModel , IFormatterResolver )
- - at MessagePack.Formatters.Ajour_Subscriptions_CompositeProjection\\.CompositeProjectionStateFormatter.Serialize(Byte[]& , Int32 , CompositeProjectionState , IFormatterResolver )
- - at MessagePack.MessagePackSerializer.Serialize[T](Stream stream, T obj, IFormatterResolver resolver)

**Comment by JulianMay** [comment]
I have no experience with MessagePack, I'm simply experimenting to see if we can replace ProtoBuff for our serialization-to-file of in-memory readmodels.
I'm using the contractless approach, like so:
`
MessagePackSerializer.Serialize(stream, toSerialize, MessagePack.Resolvers.ContractlessStandardResolver.Instance);
`

**Comment by JulianMay** [comment]
... Is there something obvious I'm not seeing here?

**Comment by neuecc** [comment]
maybe this issue is about another library.
If you mention about MessagePack for C#, related to https://github.com/neuecc/MessagePack-CSharp/issues/57

**Comment by JulianMay** [comment]
You are correct, wrong library - I'll see myself out

**Comment by yfakariya** [comment]
@neuecc thank you for follow up :)
