### ISSUE TITLE
Memory corruption

### ISSUE THREAD

**Issue by cata02** [msgpack/msgpack-cli#251]
public class c4
        {
            private c4()
            {
            }
            public c4(string b, int a)
            {
                this.B = b;
                this.A = a;
            }

            public string B { get; private set; }

            public int A { get; private set; }
        }

        [TestMethod]
        public void RezultatIncarcareScadentarTests()
        {
            var unu = new c4("A", 3);

            var s = SerializationHelpers.Serialize(unu);
            var doi = SerializationHelpers.Deserialize(s, typeof(c4)) as c4;

            //MsgPack.Serialization.SerializationContext.Default.GeneratorOption
            Assert.AreEqual(unu.A, doi.A);
            Assert.AreEqual(unu.B, doi.B);
        }
I have an weird scenario: one class with a private ctor and a public ctor initializing private set properties.
Serializing an instance like in the test result in the following bytes:
146, 3, 161, 65 (the integer followed by the string, seems to be following a ascii ascending order).

On deserialization message pack emitted code calls the public ctor (the one with 2 arguments)  trying to pass the values as on the wire: the integer for the first argument (which is a string) and a arbitrary int (the string pointer?) for the second argument.

It seems like messagepack cli is serializing properties in alphabetical order and passing them to a ctor that has the same number of arguments regardless of their type, **bypassing clr type-safety**!

The immediate window cannot display some deserialized members showing "Unable to read memory".

For classes that are more complex i got to a situation where a property of type class A was, at runtime after deserialization, on type class B.

No exceptions whatsoever.
Dumping generated ode could help understanding message pack cli behavior.

I'm on .NET 4.7/VS 2017.

**Comment by yfakariya** [comment]
Thank you for reporting!
It sounds a bug. What version did you use?

**Comment by cata02** [comment]
Latest on nuget, i think 0.8

**Comment by yfakariya** [comment]
This issue should be duplicated with #233.
Could you try 0.9.0-rc1? I will release this package as 0.9.0 unless any issues are found.

**Comment by cata02** [comment]
Will test tomorrow.
Though i'd like to understand the inner workings.

Is there a way to dump the generated serializer code to disk in order to use ILSpy/Reflector?

**Comment by yfakariya** [comment]
You can dump(and reuse) serializer code with `SerializerGenerator` class. It supports both of source code style and IL(.dll) style. There is another option named `mpu.exe` which is command line wrapper of `SerializerGenerator` and is contained in .zip file which can be downloaded from github release page.

**Comment by cata02** [comment]
It seems to be working on 0.9 rc1.

The bug seems to be around the way methods SetUnpackedValueOf are generated.
I still don't understand how the CLR compiles this code.
for my example it assigns and int to a string field.

Maybe using Roslyn for code generation for .net 4.6+ would be a reasonable idea.

**Comment by yfakariya** [comment]
Thank you!

From my experience, IL verifier heavyly relies on compilers' work. You may see a lot of strange erros and/or behaviors when you use IL emit.
Using Roslyn sounded a good idea, and I actually tried last fall, but I found that it is not so better than code DOM(and CodeDOM was appeared in corefx repo). Do you have any idea to justify migrating to Roslyn?

**Comment by cata02** [comment]
I have no experience with codedom or roslyn.
My less than 2 cents:
1. i think it would generate correct IL
2. maybe better IL, more optimized. MS seems to be focused on optimizations and performance lately.
3. it's currently maintained, codedom will no longer evolve.

Have to think about it, maybe i can have better ideas.

**Comment by yfakariya** [comment]
I misunderstood your intention. I understand you say that all code generation should be Roslyn based.

My answers are:
1. You are correct, but Roslyn needs compilation, so it requires much more time than current System.Reflection.Emit based approach (even if the Roslyn is much faster than CodeDOM).
2. It is tradeoff between serialializer generation performance and serializer runtime performance. I think this is little that the better IL brings for now.
3. Yes, but not so fantastic in terms of serializer generation.

There are other issues relating to Roslyn:
* It effectively depends on non xplat msbuild libraries yet.
* Although Roslyn supports modern syntax like async/await, this is extremely differ as IL.Emit, so abstractions may be much more complex.

**Comment by yfakariya** [comment]
Change label because the bug should be fixed.

**Comment by yfakariya** [comment]
Close because this is duplicate. It is welcome to reopen to continue discussion.
