### ISSUE TITLE
Unpack an unknown structure

### ISSUE THREAD

**Issue by dragomirg** [msgpack/msgpack-cli#267]
I have a C++ program and a C# program, which communicate and they use MessagePack for packing the messages. The C++ program uses this implementation of MessagePack: **https://github.com/camgunz/cmp**
The C++ program is "ConsoleApplication1" in the attachment. It packs some data, which can be seen in the variable "toSend.data" (you can run and debug the program with Visual Studio)
[ConsoleApplication1.zip](https://github.com/msgpack/msgpack-cli/files/1424837/ConsoleApplication1.zip)

I want to unpack the packed data "rawData" from a C# program:
**byte[] rawData = new byte[]
            {
                0xCE, 0x00, 0x63, 0xB9, 0x87, 0xCD, 0x07, 0xE8, 0xCC, 0xA5, 0xC4, 0x06, 0x50, 0x01, 0x00, 0x32,
                0x01, 0xF4,
            };**

You can see the data starts with a UInt32 value, then a UInt16 and so on. But I did not find an easy way to unpack this byte array and get the values which are stored inside. Any hints how I can unpack the byte array with C#?

**Comment by yfakariya** [comment]
Sorry for delay. Try `MessagePackSerializer.UnpackMessagePackObject` and `MessagePackObject.AsXxx()` (and `IsTypeOf()`) methods to check and extract values.

**Comment by dragomirg** [comment]
Thank you for your response. I used the following code and I managed to extract only the first value from the packed stream, could you please give me a hint what I should do in order to extract all values from the stream:


**byte[] rawData = new byte[]
            {
                0xCE, 0x00, 0x63, 0xB9, 0x87, 0xCD, 0x07, 0xE8, 0xCC, 0xA5, 0xC4, 0x06, 0x50, 0x01, 0x00, 0x32,
                0x01, 0xF4,
            };
            Stream stream = new MemoryStream(rawData);
            var rawObject =  MessagePackSerializer.UnpackMessagePackObject(stream);
            Debug.WriteLine("Type: {0}", rawObject.UnderlyingType);
            var Val_1 = rawObject.AsUInt32();**

**Comment by yfakariya** [comment]
Sorry, I'm delayed again...

`Unpacker.ReadItem()` may help you.
```c#
using ( var unpacker = Unpacker.Create( stream ) )
{
    for ( var data = unpacker.ReadItem(); data != null; data = unpacker.ReadItem() )
    {
        Debug.WriteLine( "Type: {0}", data.Value.UnderlyingType );
    }
}
```

**Comment by dragomirg** [comment]
Worked perfectly! Thank you very much :)
