### ISSUE TITLE
Order items are serialized

### ISSUE THREAD

**Issue by NextSim** [msgpack/msgpack-cli#291]
I am using this in c#.  I created a class to hold the members I need serialized.  The serializer looks like it organizes them in alphabetical order and not in the order they are in the defined class. 

So if I have two classes 

```
public class enableApiHelper
    {
        public int id { get; set; }
        public int id2 { get; set; }
        public string apiFunc { get; set; }
        public enableApiParams apiParams { get; set; }

    }

    public class enableApiParams
    {
        public bool val { get; set; }
    }
```

when I serialize them and convert to JSON I get

> [
  "enableApiControl",
  [
    true
  ],
  0,
  1
]

but it should be

> [
  0,
  1,
  "enableApiControl",
  [
    true
  ]
]

which I get when I change the class definition to

```
    public class enableApiHelper
    {
        public int aid { get; set; }
        public int bid2 { get; set; }
        public string capiFunc { get; set; }
        public enableApiParams dapiParams { get; set; }

    }
```

Is this intended?  Is there a setting I can change so it serializes in order in the class and not alphabetical?

**Comment by evgenyzdanovich** [comment]
Hi @NextSim.
If I'm not mistaken there's an option to specify order of serialization/deserialization via MessagePackMember.

This can be a little of redundant but you can specify order for every field.

`
using MsgPack.Serialization;

public class enableApiHelper
{
        [MessagePackMember(0)]
        public int id { get; set; }
        [MessagePackMember(1)]
        public int id2 { get; set; }
        [MessagePackMember(2)]
        public string apiFunc { get; set; }
        [MessagePackMember(3)]
        public enableApiParams apiParams { get; set; }
}
`

I'm not sure if we have to explicitly declare all fields to achieve this. Hope it helps :)

**Comment by NextSim** [comment]
I worked around it. Thanks
