### ISSUE TITLE
Serialize items  differently

### ISSUE THREAD

**Issue by NextSim** [msgpack/msgpack-cli#292]
I need to serialize a class where some of the class is serialized with the context set to map, but some is set to the default.

How would I create a class structure that would be able to serialize the data  so it would be formatted like the data below (in JSON)

> [
  0,
  3,
  "setCarControls",
  [
    {
      "throttle": 0.5,
      "steering": 0,
      "brake": 0,
      "handbrake": true,
      "is_manual_gear": false,
      "manual_gear": 0,
      "gear_immediate": true
    }
  ]
]

**Comment by yfakariya** [comment]
Sorry for delay.
Would you tell me sample code snippet to repro this?
