### ISSUE TITLE
Type Object in MessagePack

### ISSUE THREAD

**Issue by BradenCalderMurphy** [msgpack/msgpack-cli#333]
Hi,

When serializing a MessagePack class which has a property of type "Object" it does not retain the type when you deserialize the MessagePack class. For example, I set the Property "Value" to an Int32 number of say 16. When I deserialize the class it comes out as a byte. 
```
    [MessagePackObject]
    public class Item {

        public Item() {

        }
        [Key(0)]
        public object Value { set; get; }
    }
```
The workaround is adding something like I have below where you implement your own type Property.  Is there another better way to do this or is it working as intended?
```
    [MessagePackObject]
    public class Item {

        public Item() {

        }

        public Item(object value) {
            if (value != null) {
                if (value.GetType().IsSerializable) {
                    this.Value = value;
                    this.Type = value.GetType().ToString();
                }
            }
        }

        [Key(0)]
        public object Value { set; get; }
        [Key(1)]
        public string Type { set; get; }

        public object GetOriginalValue() {
            object val = Value;
            if (val != null) {
                val = Convert.ChangeType(val, System.Type.GetType(Type));
            }
            return val;
        }
    }
```

**Comment by yfakariya** [comment]
Sorry for delay, but the above code looks [message pack for C#](https://github.com/neuecc/MessagePack-CSharp). Handling `object` is vary from among implementations, so please ask in that repository.
