### ISSUE TITLE
[Unity][il2cpp]'class' is not registered in this resolver,resolver.StandardResolver

### ISSUE THREAD

**Issue by afeilo** [msgpack/msgpack-cli#335]
if I use il2cpp to build my app,the app throw this exception when i used msgpack

**Comment by afeilo** [comment]
i changed mono ,it is ok

**Comment by yfakariya** [comment]
Sorry for delay. But `StandardResolver` is the type of message pack for C#, its repository is [here](https://github.com/neuecc/MessagePack-CSharp/).
