### ISSUE TITLE
How to serialize and deserialize a List member in a class

### ISSUE THREAD

**Issue by rliu88** [msgpack/msgpack-cli#336]
Hi,

I am wondering whether it is possible to serialize and deserialize a list member is a class?  For example, in the below scenario, serialization of the Customer object seems working, however, when I deserialize it, all the info inside CustomerOrders are lost.  How should I fix this problem?  Thank you.

public class Order
{
   int OrderId{get;set;}
   string OrderType{get;set;}
}

public class OrderList
{
   public List<Order> Orders{get;set;}
}

public class Customer
{
   public int CustomerId{get;set;}
   public OrderList CustomerOrders{get;set;}
}

**Comment by rliu88** [comment]
Don't worry.  I figured it out.

**Comment by yfakariya** [comment]
Sorry for delay, and I am happy to hear that.
