### ISSUE TITLE
about LZ4 

### ISSUE THREAD

**Issue by huahaitao** [msgpack/msgpack-cli#338]
I used LZ4 via messagepack 1.8.74 like this:
RedisHelper.HSet("LONG", longId, LZ4MessagePackSerializer.Serialize<Long>(longInfo));
var @long= LZ4MessagePackSerializer.Deserialize<Long>(o);

and when I update it to 2.1.90
LZ4MessagePackSerializer is not supported any more. 
So what should I do ?  Especially the history data that had been generated.

Thank you!

**Comment by yfakariya** [comment]
Sorry for delayed response, and I can tell you some info. Your library is msgpack for C# by @neuecc. AFAIK, it has some incompatibilities between 1.x and 2.x. You should read migration docs in [here](https://github.com/neuecc/MessagePack-CSharp/blob/master/doc/migration.md) :).
