### ISSUE TITLE
Add additional TFM do dependencies can be optimised

### ISSUE THREAD

**Issue by thompson-tomo** [msgpack/msgpack-cli#359]
**Is your feature request related to a problem? Please describe.**
I want to minimise dependencies in my project by utilising framework dependencies wherever possible

**Describe the solution you'd like**
I want the package to have additional TFM'S which contains less dependencies. I.e. net core 3 & net 5, this will reduce maintenance effort. 

**Describe alternatives you've considered**
Accept the additional dependency

**Additional context**
n/a

**Comment by yfakariya** [comment]
Which TFMs do you want to support?

I'm thinking to support new TFMs and it looks reasonable to support only `net46` (or above), `net6`, `net8` , `netstandard2.0`, and `netstandard2.1`. Are they accetable for  you?

**Comment by thompson-tomo** [comment]
What I would propose at a min is:
- drop net standard 1.3
- drop uap
- Drop windows phone
- add net 6
- Add net standard 2.1
