### ISSUE TITLE
Update libc DllImport to one that is supported?

### ISSUE THREAD

**Issue by reifujin** [msgpack/msgpack-cli#41]
Hey,

I was trying to compile your library through the .NET Native toolchain and realised that it has a dependency on libc.dll (UnsafeNativeMethods.cs:52) for memcmp. (As a result, it doesn't run and probably fails during runtime.) I believe MSFT has deprecated libc.dll (http://msdn.microsoft.com/en-us/library/abx4dbyh.aspx) and only allows you to use libcmt or mscvrt. (It's in that tiny Note section.)

Is it possible to update this method? 

Thanks!
Connie

**Comment by JSalazar88** [comment]
Did the fix for this issue ever make it into master? We are also trying to use MsgPack in a windows store app, and are unable to, due to the libc.dll dependency. Thanks!
