### ISSUE TITLE
Unpack a unknown type (Unity3D - C#)

### ISSUE THREAD

**Issue by santiago-sgk** [msgpack/msgpack-cli#43]
Hi! I'm working on Unity3D and I tried write a code which receive data and unpack it.
The data received has been packed with MsgPack on Python, but I don't know how it was made. Now, I tried unpack the data on Unity3D/C# and I have some of problem about this because I don't know how I must do it.
I know that I must obtain from the packed data a structure with a key-values pair.
The code, which I have write like as:

		// "package" is the data received (as string)
		// "GetBytes()" take the string and return their bytes.
		var stream = new MemoryStream(GetBytes(package));
		string unpackage = string.Empty;
		for (int i = 0; i<=package.Length; i++) {
			var rawObject = Unpacking.UnpackObject (stream);
			unpackage += rawObject.ToString();
		}
		Debug.Log (unpackage);

So, the raw data, before the code:
??elevation?@@?33333?name?GnssMessage?timestamp?A??'1????longitude?@b??)S?source_timestamp?
And the data after the code:
630630101010801010118097011601050111011006306406406305105105105105106301100970109010106307101100115011507701010115011509701030101063011601050109010101150116

Can any help me?

Thanks!

**Comment by yfakariya** [comment]
Close because there are no response to this Q&A.
Please reopen it if you have additional questions. Thanks!
