### ISSUE TITLE
DateTime Max Value Does Not Roundtrip through .Pack and .Unpack

### ISSUE THREAD

**Issue by phil000** [msgpack/msgpack-cli#44]
There is a bug where DateTime max value in UTC does not roundtrip through **.Pack** and **.Unpack**

    DateTime epoch = new DateTime(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc);
    DateTime date = new DateTime(3155378975999999999L, DateTimeKind.Utc);

    var serializer = MessagePackSerializer.Get<DateTime>();

    using (MemoryStream ms = new MemoryStream())
    {
        serializer.Pack(ms, date);

        var test = ms.ToArray();

        ms.Position = 0;

        long diff = (long)date.Subtract(epoch).TotalMilliseconds;
        //=253402300800000 which cannot be added back to epoch successfully 
        //*ERROR*: epoch.AddMilliseconds(diff);

        //*ERROR*: The unpacked value is not expected type. The added or subtracted value results in an un-representable DateTime.
        DateTime result = serializer.Unpack(ms);
    }

**Comment by yfakariya** [comment]
I closed this issue because 3 months gone since it was fixed.
