### ISSUE TITLE
C# complete dynamic deserializer to dictionary

### ISSUE THREAD

**Issue by Jan-Heapster** [msgpack/msgpack-cli#47]
Hey all! Wanna use MsgPack in my AppProject. I have to handle very differtent packages, so i wanted to code a deserializer, that unpacks the msgPack to a c# Dictionary. If i have the dictionary i will check out to which function of my Server the package is adressed to (e.g. Login, general communication, ...).

My actual code looks like this:
<code>
public void Deserialize(byte[] rawMessage) {

            Dictionary<MessagePackObject, MessagePackObject> mpoDict = MessagePackSerializer.Create<Dictionary<MessagePackObject, MessagePackObject>>().Unpack(new MemoryStream(rawMessage));
            Dictionary<String, MessagePackObject> dict = mpoDict.ToDictionary(kv => (String)kv.Key, kv => kv.Value);
            MessagePackObject theValue;

            if (dict.TryGetValue("error", out theValue))
            {
                var error = (String)theValue;
            }
            else if (dict.TryGetValue("engine", out theValue))
            {
                var engine = (String)theValue;
                if(engine.Equals("@LOGIN")){Server.Client.Handler.LoginHandler(dict)}
                else if(engine.Equals("@REGISTER")){Server.Client.Handler.LoginHandler(dict)}
                else if(engine.Equals("@MESSAGE")){Server.Client.Handler.LoginHandler(dict)}
                else if(engine.Equals("@LOGOUT")){Server.Client.Handler.LoginHandler(dict)}
                else{Server.Clinet.Handler.ErrorHandler.throwError("Unrecognized Engine")}
            }
        }
</code>

some part of this seems to be not working, i get always errorstuff. Can someone help?

**Comment by yfakariya** [comment]
@Jan-Heapster 

I've written the spec draft. Would you review it? https://gist.github.com/yfakariya/fb6d5c66fa4d8a82346b

**Comment by Jan-Heapster** [comment]
Hey!

I am goin to take a detailed look on it tomorrow.
But i am very happy about to hear that you are still engaged.

CYU tomorrow

Am 11.01.2015 um 15:08 schrieb Yusuke Fujiwara:
>
> @Jan-Heapster <https://github.com/Jan-Heapster>
>
> I've written the spec draft. Would you review it? 
> https://gist.github.com/yfakariya/fb6d5c66fa4d8a82346b
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/msgpack/msgpack-cli/issues/47#issuecomment-69495627>.
>

-- 

Jan Weber / Backenddeveloper
Jan@Invitu.de <mailto:Jan@Invitu.de>/ + 49 1573 64 14 294

heapsterDev
http://www.invitu.de

**Comment by yfakariya** [comment]
@Jan-Heapster I released this feature in 0.6.0-beta2 release. Could you try it?

**Comment by yfakariya** [comment]
Fixed in 0.6.0.
