### ISSUE TITLE
How can i used the console "mono mpu.exe -s xxx"

### ISSUE THREAD

**Issue by dearlulu** [msgpack/msgpack-cli#53]
I am download the msgpack on the release and using the pre-generation to Generate a serializer file.
My Information : version : 0.5.6  os:mac 10.10

for example:
mono mpu.exe -s xxx.cs 

but it will show this log:
Source 'xxx.cs'
Line:8, Column:13
CS0246
The type or namespace name `xxx' could not be found. Are you missing an assembly reference?
I find it not reference dll and used : mono mpu.exe -s xxx.cs --references=a.dll,b.dll,c.dll(all the dll is in the project)

show log : System.IO.FileNotFoundException: Could not load file or assembly 'Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.

My xxx.dll file is copy from the project and the xxx.dll file is Special Generated ?

what can i do to resolve the problem?

**Comment by yfakariya** [comment]
Closed because 8 months gone. Please reopen for additional question.
