### ISSUE TITLE
Is there any option for mpu.exe to generate Serializers for inner class ?

### ISSUE THREAD

**Issue by shuidong** [msgpack/msgpack-cli#56]
I am developing game for IOS, so I used mpu.exe to generate pre-serializer.
Usually, I used mpu like this(on mac):

```c#
mono mpu.exe -s ClassA.cs
```

For example, to ClassA like below:
```c#
public class ClassA {
        public int a = 0;

        public class ClassB{
                //...ryaku
        }
        //...
}
```
it will generate only one result file. (ClassASerializer.cs).
Sometimes I wanna generate ClassBSerializer.cs too(For inner class).
I type 
```
mono mpu.exe -?
```
and it seems there is not related options.

Is there any option for mpu.exe to generate ClassBSerializer.cs (classB is inner class in classA) ?

Any help would be appreciated.
Thanks
shuidong

**Comment by yfakariya** [comment]
It is supported now by default.
