### ISSUE TITLE
Problem with Unpacking an array "ArgumentNullException: Key cannot be nil."

### ISSUE THREAD

**Issue by designinlife** [msgpack/msgpack-cli#61]
ArgumentNullException: Key cannot be nil.
Parameter name: key
MsgPack.MessagePackObjectDictionary.ThrowKeyNotNilException (System.String parameterName)
MsgPack.MessagePackObjectDictionary.Add (MessagePackObject key, MessagePackObject value)
MsgPack.Unpacker.UnpackSubtreeDataCore (MsgPack.MessagePackObject& result)
MsgPack.Unpacker.UnpackSubtreeData ()
MsgPack.Unpacker.ReadItemData ()
MsgPack.Unpacker.UnpackSubtreeDataCore (MsgPack.MessagePackObject& result)
MsgPack.Unpacker.UnpackSubtreeData ()
MsgPack.Unpacker.ReadItemData ()
MsgPack.Unpacker.UnpackSubtreeDataCore (MsgPack.MessagePackObject& result)
MsgPack.Unpacker.UnpackSubtreeData ()
MsgPack.Unpacker.ReadItemData ()
MsgPack.Unpacker.UnpackSubtreeDataCore (MsgPack.MessagePackObject& result)
MsgPack.Unpacker.UnpackSubtreeData ()
MsgPack.Serialization.DefaultSerializers.MsgPack_MessagePackObjectMessagePackSerializer.UnpackFromCore (MsgPack.Unpacker unpacker)
MsgPack.Serialization.MessagePackSerializer`1[MsgPack.MessagePackObject].UnpackFrom (MsgPack.Unpacker unpacker)
MsgPack.Serialization.MessagePackSerializer`1[MsgPack.MessagePackObject].Unpack (System.IO.Stream stream)

**Comment by yfakariya** [comment]
It looks underlying stream contains map instead of array, and the key was `nil`. Could you show me input data in code or the result of following:
```c#
var memStream = new MemoryStream();
stream.CopyTo(memStream);
var binary = BitConverter.ToString(memSteram.ToArray());
```

**Comment by yfakariya** [comment]
Close because there are no response in long time.
Please reopen this issue to post additional question for above answer. Thanks.
