### ISSUE TITLE
Unable to serialise class with non-settable collection

### ISSUE THREAD

**Issue by nzbart** [msgpack/msgpack-cli#62]
Microsoft mandates that classes [must not expose](https://msdn.microsoft.com/en-us/library/dn169389%28v=vs.110%29.aspx) settable collection properties. I'm not aware of any classes in the BCL that violate this rule.

Unfortunately, msgpack doesn't serialise instances that comply with this rule. JSON.NET and `System.Xml.Serialization.XmlSerializer` both use the `Add` method on the collection to support non-settable collections.

Below is a test that fails that I think should pass:

```csharp
    class CompliantClass
    {
        //compliant with Microsoft guidelines at https://msdn.microsoft.com/en-us/library/dn169389%28v=vs.110%29.aspx:
        // "X DO NOT provide settable collection properties."
        public List<int> Integers { get; private set; }

        public CompliantClass()
        {
            Integers = new List<int>();
        }
    }

    //This test currently fails, but I would like it to pass
    [Test]
    public void Given_a_class_with_non_settable_list_property_When_serialised_with_msgpack_Then_no_exception_should_be_thrown()
    {
        SerializationContext.Default.GetSerializer<CompliantClass>();
    }
```

Is there a way to get msgpack to support this style of class?

**Comment by yfakariya** [comment]
It should be supported since *Serialization namespace had been added, so it looks like a bug. I'll try to repro and investigate this. Would you tell me about your version of msgpack and your platform(.net, winrt, xamarin.ios etc.)?

**Comment by nzbart** [comment]
I'm using the latest version on NuGet on .NET 4.5.2.

**Comment by yfakariya** [comment]
Did you met a `TypeLoadException`? If so, it said that you cannot specify `internal` type directly, the type must be `public`. If not, I failed to reproduce with above code in .NET 4.5.2.

**Comment by yfakariya** [comment]
Sorry, serializer generator did not consider readonly collection typed property which has non-public setter. I'll fix in next release.

**Comment by nzbart** [comment]
Thanks!

**Comment by yfakariya** [comment]
Note: internal types are not supported, so your sample code ultimately causes `TypeLoadException`. I tested make your `CompliantClass` public.

**Comment by nzbart** [comment]
You're right. I just modified my test to better represent what I want, and noticed that it passes:

```csharp
    public class CompliantClass
    {
        //compliant with Microsoft guidelines at https://msdn.microsoft.com/en-us/library/dn169389%28v=vs.110%29.aspx:
        // "X DO NOT provide settable collection properties."
        public List<int> Integers { get; private set; }

        public CompliantClass()
        {
            Integers = new List<int>();
        }
    }

    [TestFixture]
    public class CompliantClassTests
    {
        //This test currently fails, but I would like it to pass
        [Test]
        public void Given_a_class_with_non_settable_list_property_When_round_tripped_with_msgpack_Then_the_collection_should_be_identical()
        {
            //Arrange
            var original = new CompliantClass();
            var values = new[] { 1, 5, 9 };
            original.Integers.AddRange(values);
            var serialiser = SerializationContext.Default.GetSerializer<CompliantClass>();
            var stream = new MemoryStream();

            //Act
            serialiser.Pack(stream, original);
            stream.Position = 0;
            var deserialised = serialiser.Unpack(stream);

            //Assert
            Assert.That(deserialised.Integers, Is.EqualTo(values));
        }
    }
```

Did you fix the issue, or was the problem in my original test? I'm running with 0.5.9, which I notice you released yesterday.

**Comment by yfakariya** [comment]
Yes, I did and I ran yours locally too, and I decided to add another form test case in `ComplexType.cs` and `AutoMessagePackSerializer.ttinclude` to enabl
e regression tests for all generator flavors. 
https://github.com/msgpack/msgpack-cli/commit/2246e8084535f581113aa5ccaf8ad522961e3884

Do you have any problems yet?

**Comment by nzbart** [comment]
I've upgraded to the latest NuGet package and run our unit tests. No problems identified. 

Thanks for the quick turnaround!

**Comment by yfakariya** [comment]
Not at all, sorry for inconvenience.
