### ISSUE TITLE
TypeInitializationException from MessagePackSerializer.Get<IList<MessagePackObjectDictionary>>()

### ISSUE THREAD

**Issue by benjamin-bader** [msgpack/msgpack-cli#64]
This happens on Windows Phone 8.1, in a WinRT project (not Silverlight), as a result of a security-critical method call:
```
{System.MethodAccessException: Attempt by security transparent method 'MsgPack.Serialization.SerializationContext..ctor(MsgPack.Serialization.SerializerRepository, MsgPack.PackerCompatibilityOptions)' to access security critical method 'System.Collections.Concurrent.ConcurrentDictionary`2<System.__Canon,System.__Canon>..ctor()' failed.
   at MsgPack.Serialization.SerializationContext..ctor(SerializerRepository serializers, PackerCompatibilityOptions packerCompatibilityOptions)
   at MsgPack.Serialization.SerializationContext..ctor(SerializerRepository allwaysNull)
   at MsgPack.Serialization.SerializationContext..cctor()}
```

The code that produces this exception is, in its entirety:
```csharp
private byte[] Serialize(IList<MessagePackObjectDictionary> syncInfo)
{
    return MessagePackSerializer
        .Get<IList<MessagePackObjectDictionary>>()
        .PackSingleObject(syncInfo);
}
```

**Comment by benjamin-bader** [comment]
The strange thing about this error is that nothing on ConcurrentDictionary seems to be marked as security-critical; perhaps this is another problem manifesting incorrectly.  Regardless, it happens every time.  I'll investigate this.

**Comment by yfakariya** [comment]
I found that [AllowPartiallyTrustedCallers] causes Universal Apps are not worked correctly in Windows Phone, but I could not find the difference between Store Apps and Phone Apps in terms of Code Access Security.

**Comment by benjamin-bader** [comment]
Thanks for your attention; this certainly seems like a Microsoft bug.

I was able to work around it by using the non-ConcurrentDictionary typeLock code paths (along with a few other changes, like removing BigIntegerSerializer which triggered the same bad behavior).

If you have interest, I'll be happy to make a pull request.

**Comment by yfakariya** [comment]
I'm afraid that other security failures occurred, so I tried to remove APTCA from WinRT build because it is not required in reality (see https://msdn.microsoft.com/en-us/library/windows/apps/jj657973.aspx). 
Would you try prerelease version (0.5.10-beta1) from NuGet?

**Comment by benjamin-bader** [comment]
Yes, that fix sounds much better.  I'll be able to try in about six hours.  Thank you!

**Comment by benjamin-bader** [comment]
This seems to be working fine - thanks!
