### ISSUE TITLE
Using asynchronous read from a stream with Unpacker

### ISSUE THREAD

**Issue by emersonfxbx** [msgpack/msgpack-cli#67]
Hi,
How do I use the Unpacker object with an asynchronous read (BeginRead/EndRead) ?
Should I create a separate thread and use the blocking methods ?

**Comment by yfakariya** [comment]
Yes, you should do it. There are no async API now.

**Comment by nzbart** [comment]
Is there any chance of adding an async API? How much work do you think it would be?

**Comment by yfakariya** [comment]
I will add async API if they useful, and I think it takes some weekends (sorry, I cannot use weakday time to develop OSS now). In the first place, I do not understand well for real usecase of async Unpacker API. Although I know that async I/O can reduce undesirable blocking, I don't have conviction that it is useful for deserializeration. It will affect async API design and works.
Would you teach me about your scenario to use new async API and how would you use it?

**Comment by nzbart** [comment]
We use `async` throughout our code for all I/O, and one of the APIs that we use it for is TCP sockets. We want to be able to asynchronously pack objects into a `NetworkStream`. Currently, we work around the lack of an async API in MsgPack by creating a `MemoryStream` and packing objects into that, and then asynchronously copying the contents into the socket using `NetworkStream.WriteAsync`. This is obviously less efficient than packing directly into the `NetworkStream`.

**Comment by yfakariya** [comment]
Thank you. I become to be able to imagine usage. I'll try to design it, but it may takes long time as you think because it requires async API in serializer layer such as `PackToAsync` and `UnpackFromAsync` as well as `Packer` / `Unpacker` async API.

**Comment by yfakariya** [comment]
Close because this feature was added to 0.7 with performance consideration using `BufferedStream`.
