### ISSUE TITLE
Serialize/deserialize fails on dbnull.value's

### ISSUE THREAD

**Issue by ikaney** [msgpack/msgpack-cli#70]
Tried doing a simple serialize/deserialize test with a class containing Objects and some of these were set to DBNull.Value's, it fails because of the DBNulls. Any ideas, or is this just a limitation of the solution?

**Comment by yfakariya** [comment]
Do you mean that your type has `DBNull` type field? If so, register own serializer to workaround this. If not, please show more details.

**Comment by yfakariya** [comment]
`System.DBNull` is now supported from 0.6.0 beta2.
