### ISSUE TITLE
An unhandled exception of type System.StackOverflowException occurred in System.Core.dll

### ISSUE THREAD

**Issue by phil000** [msgpack/msgpack-cli#73]
Hello,
We are getting an error - "An unhandled exception of type 'System.StackOverflowException' occurred in System.Core.dll" when trying to clone either an object directly (for unit testing) or anything that has an object property:

public class MyClass
{
  public string StringProperty { get; set; }
  public int IntProperty { get; set; }
  public object ObjectProperty { get; set; }
  public DateTime DateTimeProperty { get; set; }
}

[assembly: AssemblyFileVersion("0.5.1884.705")]
[assembly: AssemblyInformationalVersion("0.5.11")]

**Comment by phil000** [comment]
And various other data types involving object:
Dictionary<string, object> value = new Dictionary<string, object> { { "1", new object() }, { "2", new object() } };
object[] value = new object[] { new object(), new object() };
etc

**Comment by yfakariya** [comment]
It should be fixed in 0.6.0 beta2. Thank you for reporting.

**Comment by phil000** [comment]
I've had a look at this and the test now throws an error:

System.Runtime.Serialization.SerializationException: System.Object cannot be serialized.

at MsgPack.Serialization.DefaultSerializers.System_ObjectMessagePackSerializer.PackToCore(Packer packer, Object value)

Can you confirm that this is the intended behaviour to not support an actual object value in ObjectProperty?

If the ObjectProperty has a concrete type like MyClass the result after serilization\deserilization is a MgsPackObject not a MyClass as expected.


public class MyClass
 {
 public string StringProperty { get; set; }
 public int IntProperty { get; set; }
 public object ObjectProperty { get; set; }
 public DateTime DateTimeProperty { get; set; }
 }

**Comment by yfakariya** [comment]
Sorry I missed answer for this additional post.
You must qualify your `ObjectProperty` with `[MessagePackRuntimeType]` or `[MessagePackKnownType]` to enable polymorphic behavior. It is intensional because polymorphic behavior is relatively advanced feature, and it should be used carefully when the data come from external party.
