### ISSUE TITLE
Allow deserialisation of types without a parameterless constructor

### ISSUE THREAD

**Issue by drewnoakes** [msgpack/msgpack-cli#75]
WCF's DataContract deserialisation uses [`FormatterServices.GetUninitializedObject`](https://msdn.microsoft.com/en-us/library/system.runtime.serialization.formatterservices.getuninitializedobject(v=vs.110).aspx) to instantiate an instance of a type without calling a constructor. This allows types like this to be serialised and deserialised:

    public class Foo
    {
        public string Name { get; set; }

        public Foo(string name) { Name = name; }
    }

msgpack-cli version 5.0 cannot deserialise this type as it requires a parameterless constructor. Version 6 adds some support via #52, but I don't think that would help here unless the property name was also lower-case.

**Comment by yfakariya** [comment]
Althhough finally I ignored the case of member/parameter name, `Foo` is not serializable because it has setter, so the default constructor is still required.
Why are you unable to add default constructor while the type is mutable?

**Comment by drewnoakes** [comment]
I can add a default constructor, but I'd rather not as I want to force all users of the type to construct instances via a parameterised constructor, so I can perform validation on instances populated by code.

Right now I just mark these constructors as `[Obsolete("Only used for serialisation")]`. But I have a lot of these message classes and it's uglier having these.

**Comment by yfakariya** [comment]
I think you can do same thing via object initialization syntax and validation code in setter of properties. If you force to set multiple properties at once, you should not explore public setters. Do I miss some points?

**Comment by yfakariya** [comment]
I will not add `GetUninitializedObject` usage because it is not available on non desktop platform and I cannot believe it is usual situation.
It is welcome reopen this issue if you believe it is common issue. Thanks!
