### ISSUE TITLE
I want to receive and send the Japanese hiragana and kanji（漢字やひらがなを送受信したい）

### ISSUE THREAD

**Issue by st0326s** [msgpack/msgpack-cli#77]
Do you may be exchanged in any way when you want to send and receive hiragana and kanji in Japanese?

I would like to receive and send the Japanese hiragana and kanji,
I will fail to UnPack.

Please tell me if there is a caveat when you want to send the hiragana and kanji.

You can use the HttpWebRequest method in the Unity of C # and is sending and receiving.

Open the MsgPack.Net35 under the src folder in MonoDevelop,
In General of Build of Project Options
A In Mono / .Net3.5 TargetFramework
How can you build, out an error in the following
Build did not complete.

INilImplicationHandlerOnUnpackedParameter.cs of

internal interface INilImplicationHandlerOnUnpackedParameter <out TAction>: INilImplicationHandlerParameter

Is because the compile error is gone Once in Mono / .Net4.0,
Following expression might not have been allowed in .Net3.5.

<out TAction>

Please tell me.

*****************************************************************************************************************
日本語のひらがなや漢字を送信と受信したいのですが、
UnPackに失敗してしまいます。

ひらがなや漢字を送信する時の注意点があれば教えてください。

UnityのC#内でHttpWebRequestメソッドを使用して送信・受信しています。

また、srcフォルダの下のMsgPack.Net35をMonoDevelopで開き、
Project OptionsのBuildのGeneralで
TargetFrameworkを Mono/.Net3.5 にして
ビルドしたのですが、下記でエラーが出て
ビルドが完了しませんでした。

INilImplicationHandlerOnUnpackedParameter.csの

internal interface INilImplicationHandlerOnUnpackedParameter<out TAction> : INilImplicationHandlerParameter

Mono/.Net4.0にしたらコンパイルエラーがなくなったので、
下記表現は.Net3.5では許可されてないのかもしれません。

<out TAction>

解決方法があれば教えてください。

**Comment by yfakariya** [comment]
1) Msgpack for CLI uses utf-8 by default, so any Japanese chars should be transferred. Would you show me the code which writes the msgpack stream with HttpWebClient?

2) Sorry, it seems that the .csproj file is staled. What branch did you cloned, and which .sln file did uou open?

**Comment by st0326s** [comment]
1) I'm sorry in the long code
　Environment Unity4.6.2.  language C #

　UseDLL is MsgPack.dll  in Unity3D Folder with MsgPack.Cli.0.5.11.zip

using UnityEngine;
using System;
using System.IO;
using System.Net;
using System.Collections;
using System.Collections.Generic;
using MsgPack.Serialization;
using MsgPack;


    public void OnClickMsgPackDataClass()
    {

        SendData senddata = new SendData();

        senddata.testdata = new TestData();

        senddata.status = 0;

        senddata.testdata.flgs = true;
        senddata.testdata.userId = 2147483647;
        senddata.testdata.os = 9223372036854775807;
        senddata.testdata.appVersion = 1.23456f;
        senddata.testdata.osVersion = 1.23456789012345d;

        DateTime nowtime = new DateTime();
        nowtime = DateTime.Now;
        senddata.testdata.requestTimestamp = nowtime.ToString("s");
        senddata.testdata.texthiragana = "あいうえおかきくけこさしすせそ";
        senddata.testdata.textkana = "タチツテトナニヌネノハヒフヘホ";
        senddata.testdata.textkanzi = "温故知新因果応報";
        senddata.testdata.textmulti = "あイ鵜えオ科きク家こ";
        senddata.testdata.sessionkey = "db5g2IkpaLY40Kme";
        senddata.testdata.language = "ja";
        senddata.testdata.device = "iPhone5";
        senddata.testdata.userUuid = "1a12za-6315-4598-124e-azsd521486d";
        senddata.testdata.signature = "1354azadfdfsdfsdfsd44464grtgrghtththtc15b0db2a02694c20505355f";

        // --- シリアライズ
        var stream = new MemoryStream();
        var serializer = SerializationContext.Default.GetSerializer<TestData>();
        // Pack obj to stream.
        serializer.Pack(stream, senddata.testdata);

        // デバッグ用バイト配列を取り出す
        byte[] bytes = stream.GetBuffer();

        // デバッグ用UTF-8 エンコード
        string text = System.Text.Encoding.UTF8.GetString(bytes);

        Debug.Log("text=" + text);

        HttpWebRequest req = (HttpWebRequest)WebRequest.Create(JSON URL String);
        req.ContentType = "application/x-msgpack; charset=UTF-8";
        req.Method = "POST";
        req.Accept = "application/x-msgpack";

        req.ContentLength = stream.Length;

        // データの設定
        System.IO.Stream s = req.GetRequestStream();
        s.Write(stream.ToArray(), 0, stream.ToArray().Length);
        s.Close();

        HttpWebResponse wres = (HttpWebResponse)req.GetResponse();
        //応答データを受信するためのStreamを取得
        Stream receiveStream = wres.GetResponseStream();
        StreamReader readStream = new StreamReader(receiveStream, System.Text.Encoding.UTF8);

        // --- デシリアライズ
        var unpacks = serializer.Unpack(receiveStream);


    }



2)
I've used the 0.5.11 of this URL.
　　　 https://github.com/msgpack/msgpack-cli/releases/

And I have to download the Zip file from this page.　
Name is "Source code (zip)".


The procedure to open the "Mono develop Ver 4.0.1", was the build target to Mono / .Net3.5.

The opened project is "MsgPack.Net35.sln" under the "\src\MsgPack.Net35" folder.

When you build I get the following 4 errors:

\msgpack-cli-0.5.1_source\msgpack-cli-0.5.11\src\MsgPack\Serialization\INilImplicationHandlerOnUnpackedParameter.cs(63,63): Error CS1031: 型が必要です。 (CS1031) (MsgPack.Net35)

\msgpack-cli-0.5.1_source\msgpack-cli-0.5.11\src\MsgPack\Serialization\INilImplicationHandlerOnUnpackedParameter.cs(63,63): Error CS1519: 無効なトークン 'out' が クラス、構造体またはインターフェイスのメンバ宣言で使用されています。 (CS1519) (MsgPack.Net35)

\msgpack-cli-0.5.1_source\msgpack-cli-0.5.11\src\MsgPack\Serialization\INilImplicationHandlerOnUnpackedParameter.cs(74,74): Error CS1519: 無効なトークン '>' が クラス、構造体またはインターフェイスのメンバ宣言で使用されています。 (CS1519) (MsgPack.Net35)

\msgpack-cli-0.5.1_source\msgpack-cli-0.5.11\src\MsgPack\Serialization\INilImplicationHandlerOnUnpackedParameter.cs(2,2): Error CS1519: 無効なトークン '{' が クラス、構造体またはインターフェイスのメンバ宣言で使用されています。 (CS1519) (MsgPack.Net35)


3)
Add'd like to hear your, but if the above Hiragana and Kanji em 11 characters, unpack will always fail.
Could you tell me How can reason I think that there is a kind of etiquette when using the full-width?

**Comment by yfakariya** [comment]
1) I have some questions about your code. It looks like that it send msgpack stream to JSON URL, and get response from the "JSON URL" site. I'm afraid that you sent msgpack stream to the server which expect JSON formatted request and it respond back JSON encoded error message -- msgpack serializer cannot recognize such (encoded JSON) stream. 
I rewrote your code in 2 projects using `HttpListener` instead of `WebRequest.GetResponse` and test it, it worked fine in .NET 3.5 runtime. I will put the testing code in the end of this post for your information.

2) Sorry, you were right. Covariance (`out' in generic argument) was supported from C# 4 compiler. I will fix it, but you can just remove `out` qualifier from `INilImplicationHandlerOnUnpackedParameter` source now.

3) Just use `String` :)

My test codes are below:
[Client code]
```c#
static void Main( string[] args )
{
	try
	{
		Console.WriteLine("CLIENT");
		Console.ReadLine();
		// ***Begin your original code except omitting outer SendData class.***
		var testdata = new TestData();

		//status = 0;

		testdata.flgs = true;
		testdata.userId = 2147483647;
		testdata.os = 9223372036854775807;
		testdata.appVersion = 1.23456f;
		testdata.osVersion = 1.23456789012345d;

		DateTime nowtime = new DateTime();
		nowtime = DateTime.Now;
		testdata.requestTimestamp = nowtime.ToString( "s" );
		testdata.texthiragana = "あいうえおかきくけこさしすせそ";
		testdata.textkana = "タチツテトナニヌネノハヒフヘホ";
		testdata.textkanzi = "温故知新因果応報";
		testdata.textmulti = "あイ鵜えオ科きク家こ";
		testdata.sessionkey = "db5g2IkpaLY40Kme";
		testdata.language = "ja";
		testdata.device = "iPhone5";
		testdata.userUuid = "1a12za-6315-4598-124e-azsd521486d";
		testdata.signature = "1354azadfdfsdfsdfsd44464grtgrghtththtc15b0db2a02694c20505355f";

		// --- シリアライズ
		var stream = new MemoryStream();
		var serializer = SerializationContext.Default.GetSerializer<TestData>();
		// Pack obj to stream.
		serializer.Pack( stream, testdata );

		HttpWebRequest req = ( HttpWebRequest )WebRequest.Create( "http://localhost/issue77" );
		req.ContentType = "application/x-msgpack; charset=UTF-8";
		req.Method = "POST";
		req.Accept = "application/x-msgpack";

		req.ContentLength = stream.Length;

		// データの設定
		var s = req.GetRequestStream();
		s.Write( stream.ToArray(), 0, stream.ToArray().Length );
		s.Close();
		// ***End your original code***
		Console.WriteLine("SENT");
		Console.ReadLine(); 
	}
	catch ( Exception ex )
	{
		Console.WriteLine( ex );
	}
}

```
[Server code]
```c#
static void Main( string[] args )
{
	try
	{
		var serializer = MessagePackSerializer.Get<TestData>();
		Console.WriteLine( "SERVER" );

		HttpListener listener = new HttpListener();
		listener.Prefixes.Add( "http://localhost/issue77/" );
		listener.Start();
		var context = listener.GetContext();
		var unpacked = serializer.Unpack( context.Request.InputStream );
		Console.WriteLine( "hiragana:{0}", unpacked.texthiragana );
		Console.WriteLine( "katakana:{0}", unpacked.textkana );
		Console.WriteLine( "kanji   :{0}", unpacked.textkanzi );
		Console.WriteLine( "multi   :{0}", unpacked.textmulti );
		listener.Abort();
	}
	catch ( Exception ex )
	{
		Console.WriteLine( ex );
	}
}
```

Note: If you run above code in Windows, you must run server as elevated privilege (you must run the cmd.exe as adminitrator).

**Comment by st0326s** [comment]
1)
 I'm sorry to how to write misleading

 JSON URL String  is actually is the URL of the API.

 Security of relationship I have such writing.

 And server side is written in code of java.


2)

In fact, although it was built and already remove the out,
Place the crafted DLL under the Unity of Assets folder
And auto compile runs I get an error such as the following.

So it is not possible to use to build the DLL,
I've used the DLL of Unity3D folder of MsgPack.Cli.0.5.11.zip.

Be .Net and cause .Net3.5 differs from the Visual Studio of Mono in Unity
Might.

Therefore, the correct answer of how to methods and build use correctly the DLL of MsgPack
It is in that situation that no longer know.


**************** Error Detail (Unity Console View)  ****************

Internal compiler error. See the console log for more information. output was:
Unhandled Exception: System.Reflection.ReflectionTypeLoadException: The classes in the module cannot be loaded.

  at (wrapper managed-to-native) System.Reflection.Assembly:GetTypes (bool)

  at System.Reflection.Assembly.GetTypes () [0x00000] in <filename unknown>:0 

  at Mono.CSharp.RootNamespace.ComputeNamespaces (System.Reflection.Assembly assembly, System.Type extensionType) [0x00000] in <filename unknown>:0 

  at Mono.CSharp.RootNamespace.ComputeNamespace (Mono.CSharp.CompilerContext ctx, System.Type extensionType) [0x00000] in <filename unknown>:0 

  at Mono.CSharp.GlobalRootNamespace.ComputeNamespaces (Mono.CSharp.CompilerContext ctx) [0x00000] in <filename unknown>:0 

  at Mono.CSharp.Driver.LoadReferences () [0x00000] in <filename unknown>:0 

  at Mono.CSharp.Driver.Compile () [0x00000] in <filename unknown>:0 

  at Mono.CSharp.Driver.Main (System.String[] args) [0x00000] in <filename unknown>:0 


3)
Thank you for writing a sample code.

Because knowledge of the server-side is zero, you can try while examining the web.

Create as a console app in both VisualStudio,
And launch the server code exe, and if you want to do it on the run exe client code
What good?

**Comment by yfakariya** [comment]
Sorry for delayed response.
1) OK.
2) There are no special instruction you need to do. Would you show me the console log? Your pasted error message said that detailed information should be shown at "console log"...
3) Excuse me, did you ask me how to run sample program? To verify serialization, see server side console log and check whether sent Japanese characters are shown correctly.
----
遅くなりまして申し訳ありません。
1) 承知しました。
2) 特別なことをしなくても構いません。「console log」を見せてもらうことはできませんか？ 貼り付けていただいたエラーメッセージでは詳細は「console log」を見ろと書いてありますので。
3) すみません、サンプルプログラムの実行方法を聞いていますか？ 結果を確認するには、サーバ側プログラムのコンソールログを見て、送信した日本語文字が正しく表示されているかを確認していただければ。

**Comment by yfakariya** [comment]
@st0326s Has this problem solved?

**Comment by yfakariya** [comment]
Closed because 2 months gone.
