### ISSUE TITLE
I can not iOS app serialize you created from the sample source

### ISSUE THREAD

**Issue by st0326s** [msgpack/msgpack-cli#78]
I've used the DLL of Unity3D folder of MsgPack.Cli.0.5.11.zip.

By imitating ”Sample02_HandlingDynamicObject.cs”, I've created a sample application to serialize the data class,
It is to work it's Android, but it will fall it's iOS in the following.

var serializer = MessagePackSerializer.Get<PhotoEntry>( context );

I do not know if they fall somewhere still defined source, but please tell me if such methods and classes that should not be used in iOS.

*******************************************************************************
MsgPack.Cli.0.5.11.zip のUnity3Dフォルダ内のDLLを使用しました。

”Sample02_HandlingDynamicObject.cs”　のマネをして、データクラスをシリアライズするサンプルアプリを作成しましたが、Androidだと動作するのですが、iOSだと落ちてしまいます。
var serializer = MessagePackSerializer.Get<PhotoEntry>( context );
まだ定義元のどこで落ちているかはわからないのですが、iOSで使用してはいけないメソッドやクラスなどあれば教えてください。

**Comment by yfakariya** [comment]
Would you show a stack trace or actual error message?
