### ISSUE TITLE
Dictionary<string,int> can not be serialized in iOS

### ISSUE THREAD

**Issue by st0326s** [msgpack/msgpack-cli#79]
List<int> but was able to serialize "https://github.com/msgpack/msgpack-cli/issues/54" of 
Issue to reference,
I do not know how to solve Dictionary<string,int>.

iOS:8.1.2
MacOS:10.10.3
Unity:5.0.1f1

***********************************************************************************************
List<int>はhttps://github.com/msgpack/msgpack-cli/issues/54を
参考にシリアライズすることができましたが、
Dictionary<string,int>は解決する方法がわかりません。

**Comment by yfakariya** [comment]
As I stated in #54 this issue is limitation of runtime itself. Value types tend to cause troubles in iOS. You might avoid this limitation using inheritance or boxing like Dictionary<string, object> or Dictionary<string, MessagePackObject> if you can.

**Comment by st0326s** [comment]
Thanks you,
The reason I wanted to ask you.

Since countermeasures can make, so we would want to solve.

**Comment by yfakariya** [comment]
FYI, you can avoid the issue with specifying `IEqualityComparer<T>` for base constructor invocation if you wrote the dictionary subclass which inhertis Dictionary<TKey, TValue>.
See http://developer.xamarin.com/guides/ios/advanced_topics/limitations/ (it says for Xamarin, but some of them should be applied for Unity)
