### ISSUE TITLE
Xamarin: Fails to build when targeting an actual device

### ISSUE THREAD

**Issue by johnvowles** [msgpack/msgpack-cli#87]
Xamarin: Works fine when building for simulator but fails to build when targeting a device. Error is:

Error MT2002: Failed to resolve "System.Runtime.InteropServices.ComTypes.FILETIME" reference from "System.Runtime.InteropServices, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"

To replicate:

1. Create new iPhone app in Xamarin Studio
2. Add nuget package
3. Add using statement to AppDelegate
4. Add new property of type MessagePackObject to AppDelegate
5. Build (targeting an actual iPhone device)

Version Info:

msgpack-cli: 0.6.0-Beta2

Xamarin Studio
Version 5.9.1 (build 3)
Runtime:
	Mono 4.0.0 ((detached/d136b79)
	GTK+ 2.24.23 (Raleigh theme)
	Package version: 400000143

Apple Developer Tools
Xcode 6.3.2 (7718)
Build 6D2105

Xamarin.iOS
Version: 8.10.0.303 (Indie Edition)
Hash: 3c4e832
Branch: master
Build date: 2015-05-20 21:47:57-0400

**Comment by yfakariya** [comment]
I cannot reproduce this issue, but I can fix it logically. So, could you try the private build to confirm the issue fixed? 
The build is available at my onedrive : http://1drv.ms/1G3ltgi

You can try this .nupkg by creating your local source in your local computer.

**Comment by johnvowles** [comment]
I get the same error with the new version, but I discovered that if I select 'Link all assemblies' in the build settings (Project settings -> Build -> iOS Build) it works OK. 

Should I close this issue now?

**Comment by yfakariya** [comment]
Thank you for reporting. 
Please wait few days until I can try linker options -- because 1) the FILETIME reference should be removed from the new build; 2) I have never faced compilation error instead of runtime AOT error with linker option.

**Comment by yfakariya** [comment]
I could repro your problem and I removed FILETIME reference. Thank you.
