### ISSUE TITLE
When defined a CORLIB_ONLY.

### ISSUE THREAD

**Issue by MichihitoManaka** [msgpack/msgpack-cli#88]
Environment:
-using MsgPack.Unity3D.(2015/06/16, 0.6.0-beta3)
-Mac OS X Yosemite(10.10.3)
(In another matter, I am happy if you could make a unitypackage for Mac environment.)
-Unity 5.1.0f3, buildin monodevelop.
-Unity settings,
Api Compatibility Level ".NET 2.0 Subset",
CORLIB_ONLY defined.

Now the compiling is stopped, the SubtreeUnpacker.cs Line 51, 52, 53.
The reason is because has disappeared defined from line 35 ~ 38.

============================================================

35 #if !CORLIB_ONLY
36 using BooleanStack = System.Collections.Generic.Stack<System.Boolean>;
37 using Int64Stack = System.Collections.Generic.Stack<System.Int64>;
38 #endif

51		private readonly BooleanStack _isMap; // <- BooleanStack undefine.
52		private readonly Int64Stack _unpacked; // <- Int64Stack undefine.
53		private readonly Int64Stack _itemsCount; // <- Int64Stack undefine.

============================================================

Same problem in "ItemsUnpacker.Skipping.cs".
It may be present in other.

I made unitypackage(Source code registration) for Mac environment.
So I want you to tell me if I have a mistake.

Thanks,

**Comment by MichihitoManaka** [comment]
Additional(another Issues?)
When I do not define the CORLIB_ONLY.

AotHelper.EqualityComparers.cs Line 1619 ~ 1633.
System.RuntimeMethodHandle is Structure.
But it has been compared to the null.

TypeInfoEncoder.cs Line 71 ~ 72.
Is there one string argument to the Pack method?

Thanks,

**Comment by yfakariya** [comment]
CORLIB_ONLY compiler parameter switches `System.dll` dependents to others, so you must define manually when you use '.NET 2.0 subset' with source code now. I'll change the source package default.

AotHelper.EqualityComparers.cs Line 1619 - 1533 compare `Nullable<RuntimeMethodHandle>` and `null`, so it should be compiled as `!left.HasValue` by C# compiler. Do you face any compilation problem?

TypeInfoEncoder.cs Line 71 - 72 should be routed in Pack<T>, but they are not very efficient, so they should use `PackString`. Thank you.

**Comment by MichihitoManaka** [comment]
・AotHelper.EqualityComparers.cs Line 1619 - 1533

It reported a compile error in my environment.

Assets/MsgPack/Serialization/AotHelper.EqualityComparers.cs(1658,38): error CS0121: The call is ambiguous between the following methods or properties: `System.RuntimeTypeHandle.operator ==(object, System.RuntimeTypeHandle)' and `System.RuntimeTypeHandle.operator ==(System.RuntimeTypeHandle, object)'

Is this would be a problem of Unity Buildin Monodevelop?

My environment:
-Mac OS X Yosemite(10.10.3)
-Unity 5.1.0f3, buildin monodevelop.
-MsgPack.Unity3D.(2015/06/16, 0.6.0-beta3)
 This slh project, we've built manually(The described unitypackage).
 Because, our environment is Mac.

Thanks,

**Comment by MichihitoManaka** [comment]
I was mistaken.

Mistake : Monodevelop version 2.x
Correct  :  Mono version 2.x

* Add more information.
All reports are all compile error.

**Comment by MichihitoManaka** [comment]
Thank you very much!
It was confirmed Fix.

However, we still have "BooleanStack" and "Int64Stack" to SubtreeUnpacker.cs is used.

Thanks,

**Comment by yfakariya** [comment]
Sorry for delay. And I'm sorry to forgot telling the problem. Did you include sources which exist only under https://github.com/msgpack/msgpack-cli/tree/master/src/MsgPack.Unity3D.Full ? `xxxStack` for Unity are defined in CorLubOnlyHelper.cs.

**Comment by MichihitoManaka** [comment]
Thank you for your reply.
We went the "Unity Build" again in the project of "MsgPack.Unity3D.Full".
It went well all but one of the problems.

The problem is that the UnityBuild uses a MonoVersion 2.x.

Specifically, 71 line of TypeInfoEncoder.cs.
Assets/MsgPack/Serialization/Polymorphic/TypeInfoEncoder.cs(71,34): error CS1501: No overload for method `Pack' takes `2' arguments
(This is no problem if use the "Mono3.x" on MonoVedelop, but Unity is "Mono2.x".)

Thanks,

**Comment by yfakariya** [comment]
Sorry for delay.
It has been fixed in 0.6.0 because Pack<T> extension method is no longer used. Please try latest drop it also supports IL2CPP. https://github.com/msgpack/msgpack-cli/releases/tag/0.6.1.1

**Comment by MichihitoManaka** [comment]
Thank you very much.
Your work is not delayed.
It has become to our help. Good luck.

Thanks,
