### ISSUE TITLE
Why non-public type 'Test' cannot be serialized? (with code)

### ISSUE THREAD

**Issue by cryptocompress** [msgpack/msgpack-cli#89]
Hi,

running this code, i got exception from "p.Pack" but not from "s.WriteObject":

```csharp
		[Serializable]
		class Test { }

		void DoIt() {
			var test = new Test();

			var s = new System.Runtime.Serialization.DataContractSerializer(test.GetType());
			var p = MsgPack.Serialization.MessagePackSerializer.Create<Test>();

			var stream1 = new System.IO.MemoryStream();
			var stream2 = new System.IO.MemoryStream();

			s.WriteObject(stream1, test);
			p.Pack(stream2, test);
		}
```

```csharp
System.Runtime.Serialization.SerializationException: Non-public type 'Test' cannot be serialized.
   bei MsgPack.Serialization.MessagePackSerializer.ValidateType(Type type) in d:\build\msgpack-cli-latest\src\MsgPack\Serialization\MessagePackSerializer.cs:Zeile 655.
```

Why is this limitation? Is this feature planned?

Somewhat related issues are private constructors and required add methods, wich too are unnecessary for DataContractSerializer to work.

Would be superb to have this out of the box.

Thank You!

**Comment by yfakariya** [comment]
Hi. Thank you for nice question.

There are two reasons to forbid non-public types serialization. First, it should be slow because it requires reflection to implement it. Second, I think serialization is a sort of publishing, so non-public type should not be exposed via serializer.
Both of them are intentional design dicision, so I will plan when it will be truely necessary in usual.

If you have a scenario to take advantage of non-publuc type serialization, please share it.

**Comment by cryptocompress** [comment]
Hi! I fully agree with you reflection-speed concerns and technical beauty of encapsulation. Non-public types are not a requirement for me at all. You are absolutly right and provided example is flawed at this point.

My goal is to find efficient replacement for json serialization:
- size efficient on-disc format
- universally appliable: cannot change class definition, add parameterless constructor or serialization-specific methods (reflection needed)
- speed is non-goal as serialized objects are used as sort of cache for way more expensive data retrieval and aggregation
- cannot use binary formatter (external technical reasons)

Those seems to be contrary to project goals, so i have to search further.

Thank You!

**Comment by yfakariya** [comment]
Closed because it is not in scope now. Please reopen this if you find more usecase(s).
