### ISSUE TITLE
Support serialisation of IReadOnlyList<T> and IReadOnlyCollection<T>

### ISSUE THREAD

**Issue by drewnoakes** [msgpack/msgpack-cli#91]
Currently an exception is thrown if attempting to create a serialiser for a type that has a field of `IReadOnlyList<T>`.

`IList<T>` is supported. Is there any reason a read only list couldn't be supported too?

**Comment by yfakariya** [comment]
Because it was not required. And historically, I has not supported ".NET 4.5" only features so aggresively. I will add them to default collection of `SerializationContext` by default.

**Comment by drewnoakes** [comment]
Thanks for your reply. I put together a PR for this that hopefully makes it easier for you to add this feature.
