### ISSUE TITLE
how to use msgpack with unity on ios platform

### ISSUE THREAD

**Issue by hiramtan** [msgpack/msgpack-cli#94]
I still can't exactly know how to use msgpack on ios platform, if there a example or tutorial show how to use msgpack with unity3d on ios platform.

**Comment by dearlulu** [comment]
https://github.com/msgpack/msgpack-cli/issues/54 
might help you

**Comment by yfakariya** [comment]
See https://github.com/msgpack/msgpack-cli/wiki/Xamarin-and-Unity#how-to-use-in-unity3d-using-dllrecommended
Latest zip in 2015-08-16 is https://github.com/msgpack/msgpack-cli/releases/tag/0.6.1.1 . Download it and add unity3d/MsgPack.dll as new asset.

**Comment by yfakariya** [comment]
It looks solved.
