### ISSUE TITLE
This operation is not supported because interface cannot be instantiated.

### ISSUE THREAD

**Issue by bluefox** [msgpack/msgpack-cli#97]
I'm not sure if the following is entirely related to https://github.com/msgpack/msgpack-cli/issues/47, but I am wondering if this is a supported usage scenario

Following is the test class, as you can see, we have an interface ITest that is attached as part of the generic dictionary
```

    public interface ITest
    {
        int TestId { get; set; }
    }

    public class TestClass : ITest
    {
        public int TestId { get; set; }
    }

    public class TestBase
    {
        public int Id { get; set; }
        public IDictionary<int, ITest> Tests { get; set; }

        public TestBase ()
        {
            Tests = new Dictionary<int, ITest>();
        }
    }

```

When trying to serialize the TestBase, it gives the following error
This operation is not supported because 'ITest' cannot be instantiated.

When getting the serializer for TestBase

var obj = new TestBase();
var serializer = MessagePackSerializer.Get(obj.GetType());

**Comment by yfakariya** [comment]
Yes, you must use new feature of 0.6 to enable non-collection interface to be serialized because type info will be needed in deserialization.
Although it is still beta, you can try with `[MessagePackRuntimeType]` in the `Tests` property.

**Comment by yfakariya** [comment]
@bluefox 
Additional questions? You can try the feature by updating NuGet package now (>= 0.6.0).

**Comment by yfakariya** [comment]
Close because of no activities.
